# -*- coding: utf-8 -*-
"""Строки интерфейса сайта на двух языках. Содержимое документов (справочник, гайд, шапки api)
для английской версии лежит в i18n/en/ — здесь только оформление страниц."""

STR = {
    "ru": {
        "lang": "ru",
        "site": "COSSACKS 3 MODLOADER",
        "other_lang": "EN",
        "other_lang_title": "English version",
        # группы навигации
        "g.start": "НАЧАЛО",
        "g.ref": "СПРАВОЧНИК",
        "g.engine": "LUA API ДВИЖКА",
        "g.modules": "МОДУЛИ API",
        "g.data": "ДАННЫЕ ИГРЫ",
        "nav.guide": "ГАЙД",
        "nav.ref": "СПРАВОЧНИК",
        "nav.engine": "LUA API",
        "nav.modules": "МОДУЛИ",
        "nav.data": "ДАННЫЕ",
        "home.title": "Документация API",
        "home.label": "Главная",
        "home.page_title": "Cossacks 3 Modloader — документация API",
        "guide.title": "Быстрый старт",
        "guide.label": "Быстрый старт",
        "guide.summary": "Как сделать первый мод: структура, manifest.lua, события, главные функции.",
        "overview.title": "Обзор api",
        "overview.label": "Обзор api/",
        "overview.summary": "Что лежит в папке api, как вызывать из Lua и из страниц, как добавить модуль.",
        "state.title": "Состояние игры",
        "state.label": "Переменные и типы",
        "state.summary": "Все глобальные переменные и типы скриптов игры: поля, размеры, вложенность.",
        "screens.title": "Экраны игры",
        "screens.label": "Экраны и кнопки",
        "screens.summary": "Экраны интерфейса игры, их состояния и тэги кнопок.",
        "natives_link": "Нативы (GAME_API) ↗",
        "returns": "Возвращает: ",
        "no_header": "Описание в шапке файла не оформлено — смотрите исходник ниже.",
        "sec.desc": "Описание",
        "sec.funcs": "Функции",
        "sec.source": "Исходник",
        "th.func": "ФУНКЦИЯ",
        "th.desc": "ОПИСАНИЕ",
        "n_funcs": "%d функций",
        "n_lines": "%d строк",
        "source_head": "api/%s — %d строк",
        "gen.lead": "Файл генерируется, руками не правится.",
        "gen.types": "В схеме описано типов (записей) скриптов игры: <strong>%d</strong>.",
        "gen.screens": "Описано экранов: <strong>%d</strong>.",
        "gen.btn_types": "ПЕРЕМЕННЫЕ И ТИПЫ →",
        "gen.btn_screens": "ЭКРАНЫ И КНОПКИ →",
        "gen.note": "Человекочитаемая версия этих данных — в справочнике. Обновить после патча игры: <code>python tools/gen_game_api.py &lt;папка игры&gt;</code>.",
        "edit": "РЕДАКТИРОВАТЬ НА GITHUB ↗",
        "prev": "← НАЗАД",
        "next": "ДАЛЬШЕ →",
        "toc": "НА СТРАНИЦЕ",
        "search_ph": "Поиск по API…",
        "search_none": "Ничего не найдено",
        "aria_search": "Поиск",
        "aria_menu": "Меню",
        "aria_theme": "Тема",
        "default_desc": "Документация API Cossacks 3 Modloader: Lua, события, интерфейсы, замена файлов и правка скриптов игры.",
        "footer.about": "Документация API<br>Собрана из папки <code>api/</code> репозитория",
        "footer.docs": "ДОКУМЕНТЫ",
        "footer.guide": "Быстрый старт",
        "footer.ref": "Справочник",
        "footer.overview": "Обзор api/",
        "footer.data": "ДАННЫЕ",
        "footer.state": "Переменные игры",
        "footer.screens": "Экраны",
        "footer.natives": "Нативы ↗",
        "footer.project": "ПРОЕКТ",
        "footer.internals": "Устройство ↗",
        "e404.title": "Страница не найдена",
        "e404.text": "Такой страницы нет.",
        "e404.btn": "НА ГЛАВНУЮ →",
        # главная
        "stat.modules": "МОДУЛЕЙ API",
        "stat.funcs": "ФУНКЦИЙ",
        "stat.natives": "НАТИВОВ ДВИЖКА",
        "stat.screens": "ЭКРАНОВ ИГРЫ",
        "home.example": "Пример за минуту",
        "home.modules": "Модули api/",
        "home.faq": "Частые вопросы",
        "card.funcs": "%d ФУНКЦИЙ",
        "card.data": "ДАННЫЕ",
        "faq.install.q": "Как установить модлоадер?",
        "faq.install.a": "<ol><li>Собрать решение <code>Modloader For Cossacks 3.slnx</code> (Release, x86).</li><li>Скопировать в папку игры <code>Cossacks3Launcher.exe</code>, <code>Cossacks3Loader.dll</code>, основную DLL и <code>Cossacks3Cef.exe</code>.</li><li>Поставить CEF: <code>python tools/install_cef.py</code>.</li><li>Скопировать <code>api/</code> в <code>&lt;игра&gt;/modloader/api/</code>, моды — в <code>modloader/mods/</code>.</li><li>Запускать через <code>Cossacks3Launcher.exe</code>.</li></ol>",
        "faq.where.q": "Где лежат моды?",
        "faq.where.a": "<p><code>&lt;игра&gt;/modloader/mods/&lt;папка мода&gt;/</code> — внутри обязательно <code>manifest.lua</code>. Мод может быть только из данных: одни <code>assets/</code>, <code>patches/</code> или <code>content.lua</code>.</p>",
        "faq.reload.q": "Как поправить api без пересборки?",
        "faq.reload.a": "<p>Файлы <code>api/*.lua</code> лежат отдельно от DLL: поправил файл — команда <code>.lua reload</code> в консоли модлоадера.</p>",
        "faq.side.q": "Что менять на клиенте, а что на сервере?",
        "faq.side.a": "<p>Интерфейс и клавиши — <code>client</code>. Решения хоста — <code>server</code>. Всё, что меняет мир одинаково на всех машинах (баланс, статы, логика), — <code>shared</code>: иначе в сети партия разойдётся. Подробнее — <a href=\"core-sides.html\">какая сторона что умеет</a>.</p>",
        "nav.home": "ГЛАВНАЯ",
        "hero.h1": "ТА ЖЕ ИГРА.<br>ПРАВИЛА — ТВОИ.",
        "hero.p": "Новые нации, свои юниты, битвы на карте, которой в игре не было, и картинка как в кино. Ставишь моды — и Казаки 3 играются так, будто вышли вчера. Файлы игры не трогаем, откатиться можно в любой момент.",
        "hero.cta1": "ЧТО МОЖНО ПОЛУЧИТЬ ↓",
        "hero.cta2": "Я ХОЧУ ДЕЛАТЬ МОДЫ →",
        "feat.title": "Что дают моды",
        "feat.1.t": "Новые нации",
        "feat.1.d": "Монголы с конными лучниками, Запорожская Сечь. Любую нацию собирают из шаблона за пару строк.",
        "feat.2.t": "Свои юниты",
        "feat.2.d": "Сердюк-ветеран, другие цены, урон и скорость. Баланс подкручивается под то, как ты играешь.",
        "feat.3.t": "Новые битвы",
        "feat.3.d": "Исторические сражения на своих картах прямо в меню игры.",
        "feat.4.t": "Другая картинка",
        "feat.4.d": "Пресеты пост-обработки, туман, тени и свет. Игра выглядит как кино.",
        "feat.5.t": "Свой интерфейс",
        "feat.5.d": "Панель найма, HUD и меню на HTML прямо поверх игры.",
        "feat.6.t": "Играй по сети",
        "feat.6.d": "Хост сверяет моды у всех игроков, а встроенный сторож ловит рассинхрон на лету.",
        "dev.title": "Хочешь делать моды сам?",
        "dev.p": "Всё пишется на Lua. Поправил скрипт, набрал <code>.lua reload</code> — и смотришь результат в игре, без перезапуска. Ниже всё, что для этого нужно.",
        "dev.guide": "БЫСТРЫЙ СТАРТ →",
        "dev.overview": "ОБЗОР API →",
        "dev.events": "СОБЫТИЯ →",
    },
    "en": {
        "lang": "en",
        "site": "COSSACKS 3 MODLOADER",
        "other_lang": "RU",
        "other_lang_title": "Русская версия",
        "g.start": "START",
        "g.ref": "REFERENCE",
        "g.engine": "ENGINE LUA API",
        "g.modules": "API MODULES",
        "g.data": "GAME DATA",
        "nav.guide": "GUIDE",
        "nav.ref": "REFERENCE",
        "nav.engine": "LUA API",
        "nav.modules": "MODULES",
        "nav.data": "DATA",
        "home.title": "API documentation",
        "home.label": "Home",
        "home.page_title": "Cossacks 3 Modloader — API documentation",
        "guide.title": "Quick start",
        "guide.label": "Quick start",
        "guide.summary": "How to make your first mod: structure, manifest.lua, events, the main functions.",
        "overview.title": "api overview",
        "overview.label": "api/ overview",
        "overview.summary": "What is in the api folder, how to call it from Lua and from pages, how to add a module.",
        "state.title": "Game state",
        "state.label": "Variables and types",
        "state.summary": "All global variables and types of the game scripts: fields, sizes, nesting.",
        "screens.title": "Game screens",
        "screens.label": "Screens and buttons",
        "screens.summary": "The game's interface screens, their states and button tags.",
        "natives_link": "Natives (GAME_API) ↗",
        "returns": "Returns: ",
        "no_header": "The file header has no description — see the source below.",
        "sec.desc": "Description",
        "sec.funcs": "Functions",
        "sec.source": "Source",
        "th.func": "FUNCTION",
        "th.desc": "DESCRIPTION",
        "n_funcs": "%d functions",
        "n_lines": "%d lines",
        "source_head": "api/%s — %d lines (comments in Russian)",
        "gen.lead": "This file is generated and is not edited by hand.",
        "gen.types": "Types (records) of the game scripts described in the schema: <strong>%d</strong>.",
        "gen.screens": "Screens described: <strong>%d</strong>.",
        "gen.btn_types": "VARIABLES AND TYPES →",
        "gen.btn_screens": "SCREENS AND BUTTONS →",
        "gen.note": "A human-readable version of this data is in the reference. Update after a game patch: <code>python tools/gen_game_api.py &lt;game folder&gt;</code>.",
        "edit": "EDIT ON GITHUB ↗",
        "prev": "← BACK",
        "next": "NEXT →",
        "toc": "ON THIS PAGE",
        "search_ph": "Search the API…",
        "search_none": "Nothing found",
        "aria_search": "Search",
        "aria_menu": "Menu",
        "aria_theme": "Theme",
        "default_desc": "Cossacks 3 Modloader API documentation: Lua, events, interfaces, file replacement and game script patching.",
        "footer.about": "API documentation<br>Built from the repository's <code>api/</code> folder",
        "footer.docs": "DOCUMENTS",
        "footer.guide": "Quick start",
        "footer.ref": "Reference",
        "footer.overview": "api/ overview",
        "footer.data": "DATA",
        "footer.state": "Game variables",
        "footer.screens": "Screens",
        "footer.natives": "Natives ↗",
        "footer.project": "PROJECT",
        "footer.internals": "Internals ↗",
        "e404.title": "Page not found",
        "e404.text": "There is no such page.",
        "e404.btn": "HOME →",
        "stat.modules": "API MODULES",
        "stat.funcs": "FUNCTIONS",
        "stat.natives": "ENGINE NATIVES",
        "stat.screens": "GAME SCREENS",
        "home.example": "An example in a minute",
        "home.modules": "api/ modules",
        "home.faq": "FAQ",
        "card.funcs": "%d FUNCTIONS",
        "card.data": "DATA",
        "faq.install.q": "How do I install the modloader?",
        "faq.install.a": "<ol><li>Build the solution <code>Modloader For Cossacks 3.slnx</code> (Release, x86).</li><li>Copy <code>Cossacks3Launcher.exe</code>, <code>Cossacks3Loader.dll</code>, the main DLL and <code>Cossacks3Cef.exe</code> into the game folder.</li><li>Install CEF: <code>python tools/install_cef.py</code>.</li><li>Copy <code>api/</code> to <code>&lt;game&gt;/modloader/api/</code>, mods to <code>modloader/mods/</code>.</li><li>Launch through <code>Cossacks3Launcher.exe</code>.</li></ol>",
        "faq.where.q": "Where do mods go?",
        "faq.where.a": "<p><code>&lt;game&gt;/modloader/mods/&lt;mod folder&gt;/</code> — it must contain <code>manifest.lua</code>. A mod can be data-only: just <code>assets/</code>, <code>patches/</code> or <code>content.lua</code>.</p>",
        "faq.reload.q": "How do I edit the api without rebuilding?",
        "faq.reload.a": "<p>The <code>api/*.lua</code> files live separately from the DLL: edit a file, then run <code>.lua reload</code> in the modloader console.</p>",
        "faq.side.q": "What goes on the client and what on the server?",
        "faq.side.a": "<p>Interface and keys — <code>client</code>. Host decisions — <code>server</code>. Anything that changes the world identically on all machines (balance, stats, logic) — <code>shared</code>: otherwise the match desyncs online. More — <a href=\"core-sides.html\">which side can do what</a>.</p>",
        "nav.home": "HOME",
        "hero.h1": "SAME GAME.<br>YOUR RULES.",
        "hero.p": "New nations, your own units, battles on maps the game never had, and visuals that look like a movie. Drop in mods and Cossacks 3 plays like it launched yesterday. We never touch the game files, so you can roll back any time.",
        "hero.cta1": "SEE WHAT YOU GET ↓",
        "hero.cta2": "I WANT TO MAKE MODS →",
        "feat.title": "What mods give you",
        "feat.1.t": "New nations",
        "feat.1.d": "Mongols with horse archers, the Zaporozhian Sich. Any nation is built from a template in a couple of lines.",
        "feat.2.t": "Your own units",
        "feat.2.d": "A veteran Serdiuk, different prices, damage and speed. Tune the balance to how you play.",
        "feat.3.t": "New battles",
        "feat.3.d": "Historical battles on your own maps, right in the game's menu.",
        "feat.4.t": "A different look",
        "feat.4.d": "Post-processing presets, fog, shadows and light. The game looks like a movie.",
        "feat.5.t": "Your own interface",
        "feat.5.d": "A hire panel, a HUD and menus in HTML, right over the game.",
        "feat.6.t": "Play online",
        "feat.6.d": "The host checks everyone's mods, and the built-in watchdog catches desyncs on the fly.",
        "dev.title": "Want to make mods yourself?",
        "dev.p": "It's all Lua. Tweak a script, type <code>.lua reload</code> and see the result in the game with no restart. Everything you need is below.",
        "dev.guide": "QUICK START →",
        "dev.overview": "API OVERVIEW →",
        "dev.events": "EVENTS →",
    },
}

HOME_CODE = {
    "ru": {
        "client": 'input.bind("F7", function()\n    if not game.isInGame() then return end\n    local me = native.GetPlayerIndexInterfaceIO()\n    local total, count = 0, 0\n    for _, h in ipairs(objects.list(me)) do\n        local o = objects.read(h)\n        if o and not o.bdead then total, count = total + o.hp, count + 1 end\n    end\n    log.info(string.format("объектов: %d, HP всего: %d", count, total))\nend)',
        "shared": 'events.on("game.start", function()\n    balance.setHP("musketeer18", 200)\n    balance.setDamage("musketeer18", 40, 1)   -- оружие 1 — выстрел\n    balance.set("musketeer18", "price[3]", 30) -- цена в золоте\nend)',
        "server": 'net.on("give_gold", function(data, from)\n    local who = game.playerIndexOf(from)\n    local amount = math.min(tonumber(data and data.amount) or 0, 1000)\n    player(who):add("gold", amount)\n    net.broadcast("gold_given", { player = who, amount = amount })\nend)',
    },
    "en": {
        "client": 'input.bind("F7", function()\n    if not game.isInGame() then return end\n    local me = native.GetPlayerIndexInterfaceIO()\n    local total, count = 0, 0\n    for _, h in ipairs(objects.list(me)) do\n        local o = objects.read(h)\n        if o and not o.bdead then total, count = total + o.hp, count + 1 end\n    end\n    log.info(string.format("objects: %d, total HP: %d", count, total))\nend)',
        "shared": 'events.on("game.start", function()\n    balance.setHP("musketeer18", 200)\n    balance.setDamage("musketeer18", 40, 1)   -- weapon 1 — the shot\n    balance.set("musketeer18", "price[3]", 30) -- gold price\nend)',
        "server": 'net.on("give_gold", function(data, from)\n    local who = game.playerIndexOf(from)\n    local amount = math.min(tonumber(data and data.amount) or 0, 1000)\n    player(who):add("gold", amount)\n    net.broadcast("gold_given", { player = who, amount = amount })\nend)',
    },
}
