-- Сгенерировано tools/gen_game_api.py из data/scripts/lib/classes.script. Не править руками.
GAME_SCHEMA = {
  types = {
    TAIBuildingProject = {
      { name = "cid", type = "int" },
      { name = "sid", type = "string" },
      { name = "id", type = "int" },
      { name = "used", type = "bool" },
      { name = "placefound", type = "bool" },
      { name = "founded", type = "bool" },
      { name = "peasantscalled", type = "bool" },
      { name = "usage", type = "int" },
      { name = "nearx", type = "float" },
      { name = "nearz", type = "float" },
      { name = "x", type = "float" },
      { name = "y", type = "float" },
      { name = "options", type = "int" },
      { name = "attemptstostand", type = "int" },
      { name = "attemptstofindapprplace", type = "int" },
      { name = "maxpeasants", type = "int" },
      { name = "minpeasants", type = "int" },
      { name = "npeasantscalled", type = "int" },
      { name = "gohnd", type = "int" },
      { name = "curRad", type = "int" },
      { name = "curInd", type = "int" },
      { name = "maxTryDist", type = "int" },
    },
    TAIConst = {
      { name = "armyMinCount", array = { 0, 15 }, of = { type = "int" } },
      { name = "defArmyMinCount", array = { 0, 15 }, of = { type = "int" } },
      { name = "armyMaxCount", array = { 0, 15 }, of = { type = "int" } },
      { name = "maxDivers", array = { 0, 1 }, of = { type = "int" } },
    },
    TAch = {
      { name = "achid", type = "int" },
      { name = "achsid", type = "string" },
      { name = "goal", type = "int" },
      { name = "cur", type = "int" },
      { name = "status", type = "int" },
      { name = "stringtag", type = "string" },
      { name = "bbitcoded", type = "bool" },
    },
    TAchs = {
      { name = "binit", type = "bool" },
      { name = "ach", array = { 0, 255 }, of = { type = "TAch" } },
    },
    TAdviser = {
      { name = "bvisible", type = "bool" },
      { name = "benable", type = "bool" },
      { name = "bavailable", type = "bool" },
      { name = "bconstruct", type = "bool" },
      { name = "beconomy", type = "bool" },
      { name = "beconomyadvanced", type = "bool" },
      { name = "bcontrolpeasants", type = "bool" },
      { name = "bproducepeasants", type = "bool" },
      { name = "brepairbuildings", type = "bool" },
      { name = "bfillmines", type = "bool" },
      { name = "bmarketadvises", type = "bool" },
      { name = "bmanualresource", type = "bool" },
      { name = "resonfood", type = "float" },
      { name = "resonwood", type = "float" },
      { name = "resonstone", type = "float" },
      { name = "bupgrades", type = "bool" },
      { name = "bupgradesunavailable", type = "bool" },
      { name = "bquartermaster", type = "bool" },
      { name = "bsetupguards", type = "bool" },
      { name = "bproduceofficers", type = "bool" },
      { name = "bshowsquads", type = "bool" },
      { name = "settings", type = "int" },
      { name = "version", type = "int" },
    },
    TAiData = {
      { name = "basenation", type = "int" },
      { name = "bestprojects", type = "TIdeasList" },
      { name = "centerfound", type = "bool" },
      { name = "centerx", type = "float" },
      { name = "centerz", type = "float" },
      { name = "agressorssent", type = "int" },
      { name = "defencestage", type = "bool" },
      { name = "makediversion", type = "bool" },
      { name = "landbattle", type = "bool" },
      { name = "waterbattle", type = "bool" },
      { name = "controllednations", array = { 0, 23 }, of = { type = "bool" } },
      { name = "upgradeid", array = { 0, 23 }, of = { array = { 0, 63 }, of = { type = "int" } } },
      { name = "unitupg", array = { 0, 23 }, of = { array = { 0, 319 }, of = { type = "TUnitUpgrade" } } },
      { name = "uniqupg", array = { 0, 23 }, of = { type = "TUniqUpgList" } },
      { name = "developmentera", array = { 0, 23 }, of = { type = "int" } },
      { name = "mines", type = "TIntegerList" },
      { name = "orelist", type = "TIntegerList" },
      { name = "peasantlist", type = "TIntegerList" },
      { name = "freepeasant", type = "TIntegerList" },
      { name = "ailist", type = "TIntegerList" },
      { name = "buildingslist", type = "TIntegerList" },
      { name = "storelist", type = "TIntegerList" },
      { name = "milllist", type = "TIntegerList" },
      { name = "unbuildhouses", type = "TIntegerList" },
      { name = "defenders", type = "TIntegerList" },
      { name = "guards", type = "TIntegerList" },
      { name = "agressors", type = "TIntegerList" },
      { name = "freewarriors", type = "TIntegerList" },
      { name = "towers", type = "TIntegerList" },
      { name = "armylist", type = "TArmyList" },
      { name = "unitsamount", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
      { name = "avUnits", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "bool" } } },
      { name = "officer17", array = { 0, 23 }, of = { type = "int" } },
      { name = "drummer17", array = { 0, 23 }, of = { type = "int" } },
      { name = "officer18", array = { 0, 23 }, of = { type = "int" } },
      { name = "drummer18", array = { 0, 23 }, of = { type = "int" } },
      { name = "aiunit", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
      { name = "buildlink", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
      { name = "buildprojects", array = { 0, 11 }, of = { type = "TAIBuildingProject" } },
      { name = "resbalance", array = { 0, 6 }, of = { array = { 0, 2 }, of = { type = "int" } } },
      { name = "onFood", type = "int" },
      { name = "onStone", type = "int" },
      { name = "onWood", type = "int" },
      { name = "defbuildings", type = "TAiProtectedBuildingList" },
      { name = "bFlags", array = { 0, 10 }, of = { type = "bool" } },
      { name = "inittime", type = "float" },
      { name = "bhumanai", type = "bool" },
      { name = "bprogressEconomy", type = "bool" },
      { name = "bprogressConstruction", type = "bool" },
      { name = "bprogressProduce", type = "bool" },
      { name = "bprogressUpgrades", type = "bool" },
      { name = "bprogressWar", type = "bool" },
      { name = "damagedBuildings", type = "TIntegerList" },
      { name = "guardsCount", type = "int" },
      { name = "guardsTotal", type = "int" },
    },
    TAiIdea = {
      { name = "cid", type = "int" },
      { name = "id", type = "int" },
      { name = "ideatype", type = "int" },
      { name = "count", type = "int" },
      { name = "airole", type = "int" },
    },
    TAiProtectedBuilding = {
      { name = "targetHnd", type = "int" },
      { name = "aipriority", type = "int" },
      { name = "defenders", type = "TIntegerList" },
    },
    TAiProtectedBuildingList = {
      { name = "fList", type = "TPtrList" },
    },
    TArcherCell = {
      { name = "weight", type = "float" },
      { name = "trgHnd", type = "int" },
    },
    TArmy = {
      { name = "fSquadList", type = "TPtrList" },
      { name = "fIndex", type = "int" },
      { name = "fPlIndex", type = "int" },
      { name = "fOffsetCol", type = "float" },
      { name = "fOffsetRow", type = "float" },
      { name = "fSpec", type = "int" },
      { name = "fTopZone", type = "int" },
      { name = "fCurTopZone", type = "int" },
      { name = "fSpecialOrder", type = "bool" },
      { name = "fOrder", type = "TArmyOrder" },
      { name = "fX", type = "float" },
      { name = "fZ", type = "float" },
      { name = "fCurX", type = "float" },
      { name = "fCurZ", type = "float" },
      { name = "fSquadsCurX", type = "float" },
      { name = "fSquadsCurZ", type = "float" },
      { name = "fTag", type = "int" },
      { name = "fForce", type = "int" },
      { name = "fLastBattleTime", type = "float" },
      { name = "fLastArtTime", type = "float" },
      { name = "fActive", type = "bool" },
      { name = "fRegion", type = "int" },
      { name = "fOnEnemyLand", type = "bool" },
    },
    TArmyInfo = {
      { name = "infantry", type = "int" },
      { name = "shooters", type = "int" },
      { name = "cavalry", type = "int" },
      { name = "cannons", type = "int" },
      { name = "mortars", type = "int" },
      { name = "mcannons", type = "int" },
      { name = "towers", type = "int" },
      { name = "ships", type = "int" },
      { name = "force", type = "int" },
      { name = "landCount", type = "int" },
      { name = "waterCount", type = "int" },
      { name = "region", type = "int" },
      { name = "regions", type = "TIntegerList" },
      { name = "minx", type = "int" },
      { name = "maxx", type = "int" },
      { name = "miny", type = "int" },
      { name = "maxy", type = "int" },
    },
    TArmyInfoCell = {
      { name = "infantry", type = "int" },
      { name = "shooters", type = "int" },
      { name = "cavalry", type = "int" },
      { name = "cannons", type = "int" },
      { name = "mortars", type = "int" },
      { name = "mcannons", type = "int" },
      { name = "towers", type = "int" },
      { name = "ships", type = "int" },
      { name = "force", type = "int" },
      { name = "army", type = "int" },
      { name = "tag", type = "int" },
      { name = "checked", type = "bool" },
      { name = "region", type = "int" },
      { name = "regions", type = "TIntegerList" },
    },
    TArmyInfoList = {
      { name = "fList", type = "TPtrList" },
    },
    TArmyList = {
      { name = "fList", type = "TPtrList" },
    },
    TArmyOrder = {
      { name = "iType", type = "int" },
      { name = "targetUID", type = "int" },
      { name = "tag", type = "int" },
      { name = "tag2", type = "int" },
      { name = "tag3", type = "int" },
      { name = "tagFloat", type = "float" },
    },
    TBaseObj = {
      { name = "baseid", type = "int" },
    },
    TBox = {
      { name = "minx", type = "Float = 0" },
      { name = "miny", type = "Float = 0" },
      { name = "minz", type = "Float = 0" },
      { name = "maxx", type = "Float = 0" },
      { name = "maxy", type = "Float = 0" },
      { name = "maxz", type = "Float = 0" },
    },
    TCampaignProgress = {
      { name = "bexists", type = "bool" },
      { name = "campname", type = "string" },
      { name = "missname", type = "string" },
      { name = "benabled", type = "bool" },
      { name = "bvisible", type = "bool" },
      { name = "started", type = "int" },
      { name = "finished", type = "int" },
      { name = "lose", type = "int" },
      { name = "maxfinishdifficulty", type = "int" },
      { name = "storestring", type = "string" },
    },
    TCanPlaceBuildingWalls = {
      { name = "wallsprite", type = "int" },
      { name = "bwall", type = "bool" },
      { name = "bwallchecked", type = "bool" },
      { name = "bcollision", type = "bool" },
      { name = "bcollisionchecked", type = "bool" },
    },
    TChar = {
      { name = "text", type = "string" },
      { name = "width", type = "int" },
      { name = "offx", type = "int" },
      { name = "addwidth", type = "int" },
      { name = "addoffx", type = "int" },
    },
    TChatMessage = {
      { name = "sfrom", type = "string" },
      { name = "sto", type = "string" },
      { name = "text", type = "string" },
      { name = "mode", type = "int" },
      { name = "time", type = "float" },
    },
    TChatMessages = {
      { name = "count", type = "int" },
      { name = "msg", array = { 0, 63 }, of = { type = "TChatMessage" } },
    },
    TColor = {
      { name = "r", type = "Float = 1" },
      { name = "g", type = "Float = 1" },
      { name = "b", type = "Float = 1" },
      { name = "a", type = "Float = 1" },
    },
    TConst = {
      { name = "logmessage", array = { 0, nil }, of = { type = "string" } },
    },
    TCountry = {
      { name = "id", type = "int" },
      { name = "sid", type = "string" },
      { name = "members", array = { 0, 79 }, of = { type = "string" } },
      { name = "membersairole", array = { 0, 79 }, of = { type = "int" } },
      { name = "fixedproduce", array = { 0, nil }, of = { type = "TCountryFixedProduce" } },
      { name = "enabled", array = { 0, 79 }, of = { type = "string" } },
      { name = "upgrade", array = { 0, 319 }, of = { type = "TCountryUpgrade" } },
      { name = "upgradeplace", array = { 0, nil }, of = { type = "TCountryUpgradePlace" } },
      { name = "upgradelinks", array = { 0, 319 }, of = { array = { 0, 1 }, of = { type = "string" } } },
      { name = "accesscontrol", array = { 0, nil }, of = { type = "TCountryAccessControl" } },
      { name = "unitlock", array = { 0, 7 }, of = { type = "TCountryUnitLock" } },
      { name = "upgradeprivate", array = { 0, 31 }, of = { type = "string" } },
      { name = "officers", array = { 0, 24 }, of = { type = "TCountryOfficers" } },
      { name = "editorplace", array = { 0, 6 }, of = { array = { 0, 79 }, of = { type = "TCountryEditorPlace" } } },
    },
    TCountryAccessControl = {
      { name = "id", type = "string" },
      { name = "req", array = { 0, 7 }, of = { type = "string" } },
    },
    TCountryEditorPlace = {
      { name = "sid", type = "string" },
      { name = "priority", type = "int" },
    },
    TCountryFixedProduce = {
      { name = "id", type = "string" },
      { name = "build", array = { 0, 23 }, of = { type = "TCountryFixedProduceBuild" } },
    },
    TCountryFixedProduceBuild = {
      { name = "id", type = "string" },
      { name = "x", type = "int" },
      { name = "y", type = "int" },
    },
    TCountryOfficers = {
      { name = "officersid", type = "string" },
      { name = "drummersid", type = "string" },
      { name = "units", array = { 0, 11 }, of = { type = "string" } },
      { name = "formations", array = { 0, 2 }, of = { type = "TCountryOfficersFormations" } },
    },
    TCountryOfficersFormations = {
      { name = "stype", type = "string" },
      { name = "masks", array = { 0, 49 }, of = { type = "string" } },
    },
    TCountryUnitLock = {
      { name = "id", type = "string" },
      { name = "lockid", type = "string" },
      { name = "count", type = "int" },
    },
    TCountryUpgrade = {
      { name = "id", type = "string" },
      { name = "enabled", type = "bool" },
      { name = "level", type = "int" },
      { name = "branch", type = "int" },
      { name = "itype", type = "int" },
      { name = "value", type = "float" },
      { name = "iarrparam1", array = { 0, 2 }, of = { type = "int" } },
      { name = "sarrparam2", array = { 0, 19 }, of = { type = "string" } },
      { name = "price", array = { 0, 6 }, of = { type = "int" } },
      { name = "time", type = "float" },
      { name = "x", type = "int" },
      { name = "y", type = "int" },
      { name = "tooltiptype", type = "int" },
      { name = "bindividual", type = "bool" },
    },
    TCountryUpgradePlace = {
      { name = "id", type = "string" },
      { name = "upgrade", array = { 0, 91 }, of = { type = "string" } },
    },
    TCustomBuildPointsWall = {
      { name = "builderCount", type = "int" },
      { name = "builderPoints", array = { 0, 15 }, of = { type = "TPos2f" } },
    },
    TCustomObjAABB = {
      { name = "buse", type = "bool" },
      { name = "minx", type = "float" },
      { name = "maxx", type = "float" },
      { name = "miny", type = "float" },
      { name = "maxy", type = "float" },
      { name = "minz", type = "float" },
      { name = "maxz", type = "float" },
    },
    TCustomObjDecal = {
      { name = "bexists", type = "bool" },
      { name = "scale", type = "float" },
      { name = "offx", type = "float" },
      { name = "offz", type = "float" },
      { name = "angle", type = "float" },
    },
    TCustomObjPoints = {
      { name = "builderCount", type = "int" },
      { name = "builderPoints", array = { 0, 29 }, of = { type = "TPos2f" } },
      { name = "exitCount", type = "int" },
      { name = "exitPoints", array = { 0, 3 }, of = { type = "TPos3f" } },
      { name = "shotCount", type = "int" },
      { name = "shotPoints", array = { 0, 39 }, of = { type = "TCustomObjShotPoint" } },
      { name = "smokeCount", type = "int" },
      { name = "smokePoints", array = { 0, 79 }, of = { type = "TCustomObjSmokePoint" } },
      { name = "resourcePoint", type = "TPos3f" },
      { name = "aabb", type = "TCustomObjAABB" },
      { name = "decal", type = "TCustomObjDecal" },
    },
    TCustomObjShotPoint = {
      { name = "x", type = "float" },
      { name = "y", type = "float" },
      { name = "z", type = "float" },
      { name = "bcustomdir", type = "bool" },
      { name = "bcustomweaponind", type = "bool" },
      { name = "minangle", type = "float" },
      { name = "maxangle", type = "float" },
      { name = "weaponind", type = "int" },
    },
    TCustomObjSmokePoint = {
      { name = "x", type = "float" },
      { name = "y", type = "float" },
      { name = "z", type = "float" },
      { name = "nx", type = "float" },
      { name = "ny", type = "float" },
      { name = "nz", type = "float" },
    },
    TEconomy = {
      { name = "buycostmin", type = "float" },
      { name = "buycostdef", type = "float" },
      { name = "buycostmax", type = "float" },
      { name = "buyexp", type = "float" },
      { name = "buytime", type = "float" },
      { name = "sellcostmin", type = "float" },
      { name = "sellcostdef", type = "float" },
      { name = "sellcostmax", type = "float" },
      { name = "sellexp", type = "float" },
      { name = "selltime", type = "float" },
      { name = "buycost", type = "float" },
      { name = "sellcost", type = "float" },
    },
    TEnemyInfo = {
      { name = "armyInfos", type = "TArmyInfoList" },
      { name = "towers", type = "TTowerList" },
      { name = "towerMap", array = { 0, nil }, of = { array = { 0, nil }, of = { type = "float" } } },
      { name = "team", type = "int" },
      { name = "enemyMask", type = "int" },
      { name = "changed", type = "bool" },
      { name = "enabled", type = "bool" },
      { name = "maxArmyForce", type = "int" },
    },
    TEnemyInfoList = {
      { name = "fList", type = "TPtrList" },
    },
    TFonts = {
      { name = "font", type = "string" },
      { name = "chars", array = { 0, 255 }, of = { type = "TChar" } },
    },
    TFormation = {
      { name = "id", type = "int" },
      { name = "sid", type = "string" },
      { name = "symmetry", type = "int" },
      { name = "bonusdamage", type = "int" },
      { name = "bonusshield", type = "int" },
      { name = "bonusdamagehold", type = "int" },
      { name = "bonusshieldhold", type = "int" },
      { name = "width", type = "int" },
      { name = "height", type = "int" },
      { name = "countunits", type = "int" },
      { name = "countofficers", type = "int" },
      { name = "mask", array = { 0, 23 }, of = { array = { 0, 53 }, of = { type = "bool" } } },
      { name = "maskofficers", array = { 0, 23 }, of = { array = { 0, 53 }, of = { type = "bool" } } },
    },
    TGeneratorBitmapMask = {
      { name = "r", type = "float" },
      { name = "g", type = "float" },
      { name = "b", type = "float" },
      { name = "terrain", type = "int" },
      { name = "water", type = "int" },
      { name = "forest", type = "int" },
      { name = "bsmooth", type = "bool" },
      { name = "broad", type = "bool" },
    },
    TGridList = {
      { name = "fCount", type = "int" },
      { name = "fCapacity", type = "int" },
      { name = "fGrowthDelta", type = "int" },
      { name = "fBufferItem", type = "Pointer" },
      { name = "fPackMode", type = "bool" },
      { name = "fExternalMemory", type = "bool" },
      { name = "fResetsMemory", type = "bool" },
      { name = "fBaseList", type = "Pointer" },
      { name = "fItemSize", type = "int" },
      { name = "fMatCount", array = { 0, 8 }, of = { type = "int" } },
      { name = "fPlCount", array = { 0, 11 }, of = { type = "int" } },
      { name = "fMask", type = "Integer = 0" },
      { name = "fPlMask", type = "Integer = 0" },
      { name = "fChecked", type = "Boolean = false" },
      { name = "owner", type = "int" },
      { name = "dist", type = "int" },
      { name = "fSELastCheckMask", type = "int" },
      { name = "fSELastCheckPlMask", type = "int" },
      { name = "fSELastCheckTime", type = "float" },
      { name = "fSELastCheckResult", type = "bool" },
    },
    TGroup = {
      { name = "id", type = "string" },
      { name = "count", type = "int" },
      { name = "maxcount", type = "int" },
      { name = "adddamage", type = "int" },
      { name = "addshield", type = "int" },
      { name = "posx", type = "float" },
      { name = "posy", type = "float" },
      { name = "dir", type = "float" },
    },
    TIdeasList = {
      { name = "fList", type = "TPtrList" },
    },
    TInt32 = {
      { name = "data", array = { 0, 3 }, of = { type = "byte" } },
    },
    TIntegerList = {
      { name = "fCount", type = "int" },
      { name = "fCapacity", type = "int" },
      { name = "fGrowthDelta", type = "int" },
      { name = "fBufferItem", type = "Pointer" },
      { name = "fPackMode", type = "bool" },
      { name = "fDebug", type = "bool" },
      { name = "fExternalMemory", type = "bool" },
      { name = "fResetsMemory", type = "bool" },
      { name = "fBaseList", type = "Pointer" },
      { name = "fItemSize", type = "int" },
    },
    TInterface = {
      { name = "buttons", type = "TInterfaceButtons" },
      { name = "control", type = "TInterfaceControl" },
      { name = "states", type = "TInterfaceStates" },
      { name = "gamemode", type = "int" },
      { name = "settings", type = "int" },
      { name = "statplayer", type = "int" },
      { name = "statpage", type = "int" },
      { name = "newspage", type = "int" },
      { name = "newspanellink", type = "string" },
      { name = "bhideobjectives", type = "bool" },
      { name = "showobjectivestimer", type = "float" },
      { name = "bupdateobjectivestext", type = "bool" },
    },
    TInterfaceButtons = {
      { name = "bstandground", type = "bool" },
      { name = "bnostandground", type = "bool" },
      { name = "battack", type = "bool" },
      { name = "benableattack", type = "bool" },
      { name = "bdisableattack", type = "bool" },
      { name = "bguard", type = "bool" },
      { name = "bcancelguard", type = "bool" },
      { name = "bsquadfill", type = "bool" },
      { name = "bsquaddisband", type = "bool" },
      { name = "bsquadrank", type = "bool" },
      { name = "bsquadcolumn", type = "bool" },
      { name = "bsquadsquare", type = "bool" },
      { name = "brally", type = "bool" },
    },
    TInterfaceControl = {
      { name = "bshowunitslist", type = "bool" },
      { name = "bshowcontrol", type = "bool" },
      { name = "bshowproduce", type = "bool" },
      { name = "bshowupgrade", type = "bool" },
      { name = "bshowmarket", type = "bool" },
      { name = "bshowinside", type = "bool" },
      { name = "bshowuniticon", type = "bool" },
      { name = "bshowunitinfo", type = "bool" },
    },
    TInterfaceStates = {
      { name = "bstandground", type = "bool" },
      { name = "bnostandground", type = "bool" },
      { name = "battack", type = "bool" },
      { name = "benableattack", type = "bool" },
      { name = "bdisableattack", type = "bool" },
      { name = "bguard", type = "bool" },
      { name = "bsquadrank", type = "bool" },
      { name = "bsquadcolumn", type = "bool" },
      { name = "bsquadsquare", type = "bool" },
      { name = "brally", type = "bool" },
    },
    TInternetShell = {
      { name = "lanid", type = "int" },
      { name = "nick", type = "string" },
      { name = "mail", type = "string" },
      { name = "pass", type = "string" },
      { name = "key", type = "string" },
      { name = "selclientid", type = "int" },
      { name = "selsessionid", type = "int" },
      { name = "selrankingid", type = "int" },
      { name = "currentpage", type = "int" },
      { name = "currentsessionid", type = "int" },
      { name = "currentsession", type = "TInternetShellSession" },
      { name = "currentrankingpage", type = "int" },
      { name = "profile", type = "TInternetShellProfile" },
      { name = "profiletmp", type = "TInternetShellProfile" },
      { name = "clients", type = "TInternetShellClients" },
      { name = "sessions", type = "TInternetShellSessions" },
      { name = "rankings", type = "TInternetShellRankings" },
      { name = "rankingslastupdate", type = "float" },
      { name = "chatind", type = "int" },
      { name = "chat", array = { 0, 255 }, of = { type = "string" } },
      { name = "roomchatind", type = "int" },
      { name = "roomchat", array = { 0, 255 }, of = { type = "string" } },
      { name = "historyscrollind", type = "int" },
      { name = "historyind", type = "int" },
      { name = "history", array = { 0, 255 }, of = { type = "string" } },
      { name = "bshowroom", type = "bool" },
      { name = "bshowranking", type = "bool" },
      { name = "bshowprofile", type = "bool" },
      { name = "bjoin", type = "bool" },
      { name = "bprivate", type = "bool" },
      { name = "bratingroom", type = "bool" },
      { name = "bhistoricalbattle", type = "bool" },
      { name = "bauth", type = "bool" },
      { name = "bautosearch", type = "bool" },
      { name = "bcustomautosearch", type = "bool" },
      { name = "autosearchstarttime", type = "float" },
      { name = "autosearchtotaltime", type = "float" },
      { name = "autosearchhistorytotaltime", type = "float" },
      { name = "autosearchroomtime", type = "float" },
      { name = "autosearchrealstarttime", type = "float" },
      { name = "autosearchsettings", type = "int" },
      { name = "autosearchantispamlasttime", type = "float" },
      { name = "qprequeststart", type = "float" },
      { name = "qprequeststop", type = "float" },
      { name = "qprequeststartgame", type = "float" },
      { name = "qprequeststartgameplcount", type = "int" },
      { name = "qprequeststartgamename", type = "string" },
      { name = "qprequestterminate", type = "float" },
      { name = "qprequestcloseroom", type = "float" },
      { name = "qprequestsleep", type = "float" },
      { name = "qprequestsign", type = "float" },
      { name = "qprequestmakematch", type = "float" },
      { name = "qprequestmapname", type = "string" },
      { name = "qprankedgame", type = "bool" },
      { name = "mirrormatchscore", type = "int" },
      { name = "showrankingseasonoffset", type = "int" },
      { name = "autosearchteam", type = "int" },
      { name = "prevstate", type = "int" },
      { name = "roomdata", type = "string" },
      { name = "autosearchdocreate", type = "string" },
    },
    TInternetShellClient = {
      { name = "lanid", type = "int" },
      { name = "nick", type = "string" },
      { name = "country", type = "string" },
      { name = "score", type = "int" },
      { name = "dlc", type = "int" },
      { name = "pur", type = "int" },
      { name = "ram", type = "int" },
      { name = "prevscore", type = "int" },
      { name = "prevgamesplayed", type = "int" },
      { name = "prevgameswin", type = "int" },
      { name = "state", type = "int" },
      { name = "gamesplayed", type = "int" },
      { name = "gameswin", type = "int" },
      { name = "lastgame", type = "string" },
      { name = "info", type = "string" },
      { name = "ping", type = "int" },
      { name = "bmute", type = "bool" },
      { name = "states", type = "TInternetShellClientStates" },
      { name = "sic", type = "int" },
      { name = "si1", type = "int" },
      { name = "si2", type = "int" },
      { name = "si3", type = "int" },
      { name = "snc", type = "string" },
      { name = "sn1", type = "string" },
      { name = "sn2", type = "string" },
      { name = "sn3", type = "string" },
    },
    TInternetShellClientStates = {
      { name = "bplay", type = "bool" },
      { name = "bmaster", type = "bool" },
      { name = "bsession", type = "bool" },
      { name = "bonline", type = "bool" },
    },
    TInternetShellClients = {
      { name = "fList", type = "TPtrList" },
    },
    TInternetShellProfile = {
      { name = "lanid", type = "int" },
      { name = "nick", type = "string" },
      { name = "mail", type = "string" },
      { name = "pass", type = "string" },
      { name = "info", type = "string" },
      { name = "country", type = "string" },
    },
    TInternetShellRanking = {
      { name = "ind", type = "int" },
      { name = "lanid", type = "int" },
      { name = "nick", type = "string" },
      { name = "score", type = "int" },
      { name = "rank", type = "int" },
      { name = "wins", type = "int" },
      { name = "games", type = "int" },
      { name = "states", type = "TInternetShellClientStates" },
    },
    TInternetShellRankings = {
      { name = "fList", type = "TPtrList" },
    },
    TInternetShellSession = {
      { name = "gamename", type = "string" },
      { name = "mapname", type = "string" },
      { name = "maxplayers", type = "int" },
      { name = "masterid", type = "int" },
      { name = "clientscount", type = "int" },
      { name = "blocked", type = "bool" },
      { name = "bclosed", type = "bool" },
    },
    TInternetShellSessions = {
      { name = "fList", type = "TPtrList" },
    },
    TIslandInfo = {
      { name = "index", type = "int" },
      { name = "shore", type = "bool" },
      { name = "checked", type = "bool" },
    },
    TIslands = {
      { name = "count", type = "int" },
      { name = "grid", array = { 0, nil }, of = { array = { 0, nil }, of = { type = "TIslandInfo" } } },
    },
    TLanRecreate = {
      { name = "brecreate", type = "bool" },
      { name = "brecreatestarted", type = "bool" },
      { name = "brecreatefinished", type = "bool" },
      { name = "hostid", type = "int" },
      { name = "clientcount", type = "int" },
      { name = "joinedcount", type = "int" },
      { name = "createdtime", type = "float" },
    },
    TLanSyncData = {
      { name = "playerstosync", type = "Word" },
      { name = "economyfieldstosync", array = { 0, 11 }, of = { type = "Byte" } },
      { name = "netplayer", array = { 0, 11 }, of = { type = "TLanSyncPlayerData" } },
    },
    TLanSyncPlayerData = {
      { name = "plind", type = "Byte" },
      { name = "idlepeasants", type = "Word" },
      { name = "idlemines", type = "Word" },
      { name = "workersonres", array = { 0, 6 }, of = { type = "Word" } },
      { name = "squadsuids", type = "TIntegerList" },
      { name = "squadstime", type = "TIntegerList" },
    },
    TLogMessage = {
      { name = "id", type = "int" },
      { name = "s1", type = "string" },
      { name = "s2", type = "string" },
      { name = "time", type = "float" },
      { name = "ballowdublicates", type = "bool" },
    },
    TLogMessages = {
      { name = "count", type = "int" },
      { name = "msg", array = { 0, 7 }, of = { type = "TLogMessage" } },
    },
    TMap = {
      { name = "name", type = "string" },
      { name = "gamestage", type = "int" },
      { name = "lastenvuid", type = "int" },
      { name = "dlcs", type = "int" },
      { name = "brating", type = "bool" },
      { name = "bbattle", type = "bool" },
      { name = "battlestage", type = "int" },
      { name = "battleind", type = "int" },
      { name = "battlemap", type = "string" },
      { name = "settings", type = "TMapSettings" },
      { name = "players", array = { 0, 11 }, of = { type = "TMapPlayer" } },
      { name = "playersinfo", array = { 0, 11 }, of = { type = "TMapPlayerInfo" } },
    },
    TMapPlayer = {
      { name = "id", type = "int" },
      { name = "cid", type = "int" },
      { name = "csid", type = "string" },
      { name = "name", type = "string" },
      { name = "team", type = "int" },
      { name = "color", type = "int" },
      { name = "lanid", type = "int" },
      { name = "startx", type = "float" },
      { name = "starty", type = "float" },
      { name = "aidifficulty", type = "int" },
      { name = "bexists", type = "bool" },
      { name = "bai", type = "bool" },
      { name = "bhuman", type = "bool" },
      { name = "bclosed", type = "bool" },
      { name = "bready", type = "bool" },
      { name = "bloaded", type = "bool" },
      { name = "bleave", type = "bool" },
    },
    TMapPlayerInfo = {
      { name = "sic", type = "int" },
      { name = "si1", type = "int" },
      { name = "si2", type = "int" },
      { name = "si3", type = "int" },
      { name = "snc", type = "string" },
      { name = "sn1", type = "string" },
      { name = "sn2", type = "string" },
      { name = "sn3", type = "string" },
    },
    TMapSettings = {
      { name = "gen", type = "TMapSettingsGen" },
      { name = "additional", type = "TMapSettingsAdditional" },
    },
    TMapSettingsAdditional = {
      { name = "activeoption", type = "int" },
      { name = "startingunits", type = "int" },
      { name = "balloon", type = "int" },
      { name = "cannons", type = "int" },
      { name = "peacetime", type = "int" },
      { name = "century18", type = "int" },
      { name = "capture", type = "int" },
      { name = "marketdip", type = "int" },
      { name = "teams", type = "int" },
      { name = "autosave", type = "int" },
      { name = "limit", type = "int" },
      { name = "gamespeed", type = "int" },
      { name = "adviserassistant", type = "int" },
    },
    TMapSettingsGen = {
      { name = "randkey0", type = "int" },
      { name = "randkey1", type = "int" },
      { name = "mapsize", type = "int" },
      { name = "terraintype", type = "int" },
      { name = "relieftype", type = "int" },
      { name = "resourcestart", type = "int" },
      { name = "resourcemines", type = "int" },
      { name = "season", type = "int" },
    },
    TMapTerrainData = {
      { name = "lastsavetime", type = "float" },
      { name = "objectcount", array = { 0, 15 }, of = { type = "int" } },
      { name = "tile", array = { 0, 639 }, of = { array = { 0, 639 }, of = { type = "TMapTerrainDataTile" } } },
    },
    TMapTerrainDataTile = {
      { name = "height", type = "float" },
      { name = "tex", type = "int" },
      { name = "collision", array = { 0, 3 }, of = { type = "int" } },
    },
    TObj = {
      { name = "baseid", type = "int" },
      { name = "id", type = "int" },
      { name = "uid", type = "int" },
      { name = "pl", type = "int" },
      { name = "cid", type = "int" },
      { name = "hp", type = "int" },
      { name = "kill", type = "int" },
      { name = "resamount", type = "int" },
      { name = "restype", type = "int" },
      { name = "buildprogress", type = "float" },
      { name = "bdead", type = "bool" },
      { name = "bbuilt", type = "bool" },
      { name = "bstandground", type = "bool" },
      { name = "bsearchenemy", type = "bool" },
      { name = "insideofuid", type = "int" },
      { name = "insidereserved", type = "int" },
      { name = "squad", type = "int" },
      { name = "brally", type = "bool" },
      { name = "rallyx", type = "float" },
      { name = "rallyy", type = "float" },
      { name = "rallytmpx", type = "float" },
      { name = "rallytmpy", type = "float" },
      { name = "standtime", type = "float" },
      { name = "attackdelay", type = "float" },
      { name = "attackmaxdelay", type = "float" },
      { name = "exitdelay", type = "float" },
      { name = "lastprogresstime", type = "float" },
      { name = "progresstick", type = "int" },
      { name = "idlegridx", type = "int" },
      { name = "idlegridy", type = "int" },
      { name = "scangridx", type = "int" },
      { name = "scangridy", type = "int" },
      { name = "ctrlgroupmask", type = "int" },
      { name = "bpathrequested", type = "bool" },
      { name = "bleaverequested", type = "bool" },
      { name = "bhiderequested", type = "bool" },
      { name = "trghnd", type = "int" },
      { name = "topzone", type = "int" },
      { name = "scenariogroupid", type = "int", bytes = 1 },
      { name = "smokecount", type = "int", bytes = 1 },
      { name = "wallvariation", type = "int", bytes = 1 },
      { name = "inbattle", type = "bool" },
      { name = "artx", type = "float" },
      { name = "arty", type = "float" },
      { name = "arthnd", type = "int" },
      { name = "artdistfactor", type = "float" },
      { name = "uniqrnd", type = "float" },
      { name = "individual", type = "TObjIndividualUpgrades" },
      { name = "orders", array = { 0, 11 }, of = { type = "TOrder" } },
      { name = "sndwalkproc", type = "bool" },
      { name = "sndwalkdst", type = "float" },
      { name = "sndwalktype", type = "int" },
      { name = "prevstouid", type = "int" },
      { name = "lastsearchenemy", type = "float" },
      { name = "lasttimecheckcapture", type = "float" },
      { name = "lasttimeidlegrid", type = "float" },
      { name = "lasttimescangrid", type = "float" },
      { name = "lasttimetopology", type = "float" },
      { name = "lasttimebestposition", type = "float" },
    },
    TObjBase = {
      { name = "sid", type = "string" },
      { name = "maxhp", type = "int" },
      { name = "shield", type = "int" },
      { name = "price", array = { 0, 6 }, of = { type = "int" } },
      { name = "buildtime", type = "float" },
      { name = "fishingspeed", type = "int" },
      { name = "fishingmax", type = "int" },
      { name = "speed", type = "float" },
      { name = "protection", array = { 0, 9 }, of = { type = "int" } },
      { name = "weapon", array = { 0, 3 }, of = { type = "TObjWeapon" } },
      { name = "bproduceenabled", type = "bool" },
    },
    TObjIndividualUpgrades = {
      { name = "benabled", type = "bool" },
      { name = "upglevel", type = "int" },
      { name = "attackrate", type = "float" },
      { name = "addpeasantabsorber", type = "int" },
      { name = "addtransport", type = "int" },
    },
    TObjProp = {
      { name = "id", type = "int" },
      { name = "sid", type = "string" },
      { name = "peasantabsorber", type = "int" },
      { name = "transport", type = "int" },
      { name = "material", type = "int" },
      { name = "radius", type = "float" },
      { name = "rotatespeed", type = "float" },
      { name = "costpercent", type = "float" },
      { name = "weapon", array = { 0, 3 }, of = { type = "TObjWeaponStatic" } },
      { name = "searchradius", type = "float" },
      { name = "minattackradius", type = "float" },
      { name = "cankill", array = { 0, 8 }, of = { type = "bool" } },
      { name = "mmask", type = "int" },
      { name = "kmask", type = "int" },
      { name = "vision", type = "int" },
      { name = "consume", array = { 0, 6 }, of = { type = "int" } },
      { name = "explmedia", type = "int" },
      { name = "explradius", type = "float" },
      { name = "media", type = "int" },
      { name = "score", type = "int" },
      { name = "motionstyle", type = "int" },
      { name = "usage", type = "int" },
      { name = "artdepo", array = { 0, 3 }, of = { type = "int" } },
      { name = "artind", type = "int" },
      { name = "farm", type = "int" },
      { name = "resourcebase", array = { 0, 6 }, of = { type = "bool" } },
      { name = "produce", array = { 0, 6 }, of = { type = "int" } },
      { name = "bbuilding", type = "bool" },
      { name = "bwall", type = "bool" },
      { name = "bgate", type = "bool" },
      { name = "bslowdeath", type = "bool" },
      { name = "bcapture", type = "bool" },
      { name = "bcancapture", type = "bool" },
      { name = "bprotector", type = "bool" },
      { name = "bshotdirection", type = "bool" },
      { name = "bshotforward", type = "bool" },
      { name = "bshotleftflank", type = "bool" },
      { name = "bshotrightflank", type = "bool" },
      { name = "bshotback", type = "bool" },
      { name = "bshowdelay", type = "bool" },
      { name = "bturnoff", type = "bool" },
      { name = "bstandground", type = "bool" },
      { name = "bnohungry", type = "bool" },
      { name = "bdrummer", type = "bool" },
      { name = "bofficer", type = "bool" },
      { name = "bmercenary", type = "bool" },
      { name = "bfastunit", type = "bool" },
      { name = "bpriest", type = "bool" },
      { name = "bartillery", type = "bool" },
      { name = "bartdepo", type = "bool" },
      { name = "bartprepare", type = "bool" },
      { name = "bmarket", type = "bool" },
      { name = "bcansetrally", type = "bool" },
      { name = "airole", type = "int" },
      { name = "aiforce", type = "int" },
      { name = "walkintervalfactor", type = "float" },
      { name = "exitmaxdelay", type = "float" },
    },
    TObjWeapon = {
      { name = "damage", type = "int" },
      { name = "damageinit", type = "int" },
      { name = "damagestatic", type = "int" },
      { name = "damagepercent", type = "int" },
      { name = "radiusmax", type = "float" },
      { name = "pause", type = "float" },
      { name = "dispertion", type = "float" },
    },
    TObjWeaponStatic = {
      { name = "enabled", type = "bool" },
      { name = "radiusmin", type = "float" },
      { name = "addradius", type = "float" },
      { name = "detectradiusmin", type = "float" },
      { name = "detectradiusmax", type = "float" },
      { name = "cost", array = { 0, 6 }, of = { type = "int" } },
      { name = "weaponsid", type = "string" },
      { name = "weaponid", type = "int" },
      { name = "kind", type = "int" },
      { name = "attmask", type = "int" },
      { name = "fxshot", type = "string" },
    },
    TOrder = {
      { name = "itype", type = "int" },
      { name = "info", type = "TOrderInfo" },
      { name = "bexecute", type = "bool" },
      { name = "bremove", type = "bool" },
      { name = "static", type = "bool" },
    },
    TOrderInfo = {
      { name = "trg", type = "int" },
      { name = "x", type = "float" },
      { name = "y", type = "float" },
      { name = "dx", type = "float" },
      { name = "dy", type = "float" },
      { name = "dir", type = "float" },
      { name = "z", type = "float" },
      { name = "upgradeid", type = "int" },
      { name = "produceid", type = "int" },
      { name = "restype", type = "int" },
      { name = "amount", type = "int" },
      { name = "progress", type = "float" },
    },
    TPlayer = {
      { name = "id", type = "int" },
      { name = "objbase", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "TObjBase" } } },
      { name = "cid", type = "int" },
      { name = "csid", type = "string" },
      { name = "res", array = { 0, 6 }, of = { type = "int" } },
      { name = "setres", array = { 0, 6 }, of = { type = "int" } },
      { name = "lanres", array = { 0, 6 }, of = { type = "int" } },
      { name = "resefficiency", array = { 0, 23 }, of = { array = { 0, 6 }, of = { type = "int" } } },
      { name = "fieldlife", type = "int" },
      { name = "victorystate", type = "int" },
      { name = "victorystategametime", type = "float" },
      { name = "unitcount", type = "int" },
      { name = "farm", type = "int" },
      { name = "myplmask", type = "int" },
      { name = "enemyplmask", type = "int" },
      { name = "team", type = "int" },
      { name = "difficulty", type = "int" },
      { name = "bexists", type = "bool" },
      { name = "bgeology", type = "bool" },
      { name = "bballoon", type = "bool" },
      { name = "bfamine", type = "bool" },
      { name = "brebellion", type = "bool" },
      { name = "bai", type = "bool" },
      { name = "bneutral", type = "bool" },
      { name = "aidata", type = "TAiData" },
      { name = "squads", type = "TSquadList" },
      { name = "lastattacktime", type = "float" },
      { name = "lastprogresstime", type = "float" },
      { name = "lastcheckexists", type = "float" },
      { name = "lastcalcsquadsmovecounttime", type = "float" },
      { name = "lastprogressaitime", type = "float" },
      { name = "lastseedwheattime", type = "float" },
      { name = "progresstick", type = "int" },
      { name = "searchenemyprev", type = "int" },
      { name = "searchenemylast", type = "int" },
      { name = "searchenemycur", type = "int" },
      { name = "searchenemylasttime", type = "float" },
      { name = "artlimit", array = { 0, 3 }, of = { type = "int" } },
      { name = "artcount", array = { 0, 3 }, of = { type = "int" } },
      { name = "counter", type = "TPlayerCounters" },
      { name = "stat", type = "TPlayerStatistics" },
      { name = "upgstate", array = { 0, 23 }, of = { array = { 0, 319 }, of = { type = "TPlayerUpgradeState" } } },
      { name = "lists", type = "TPlayerLists" },
      { name = "playeradviser", type = "TPlayerAdviser" },
    },
    TPlayerAdviser = {
      { name = "adviser", type = "TAdviser" },
      { name = "buildings", type = "TIntegerList" },
      { name = "upgradeseconomy", type = "TIntegerList" },
      { name = "upgradesmilitary", type = "TIntegerList" },
      { name = "produce", type = "TIntegerList" },
      { name = "squads", type = "TPtrList" },
      { name = "officers", type = "TIntegerList" },
      { name = "drummers", type = "TIntegerList" },
      { name = "peasants", type = "TIntegerList" },
    },
    TPlayerAdviserSquad = {
      { name = "cid", type = "int" },
      { name = "id", type = "int" },
      { name = "count", type = "int" },
      { name = "bofficers", type = "bool" },
    },
    TPlayerArgs = {
      { name = "fid", type = "int" },
      { name = "fposx", type = "float" },
      { name = "fposy", type = "float" },
      { name = "fposz", type = "float" },
      { name = "fvisposx", type = "float" },
      { name = "fvisposz", type = "float" },
      { name = "fdirx", type = "float" },
      { name = "fdirz", type = "float" },
      { name = "ftrgx", type = "float" },
      { name = "ftrgy", type = "float" },
      { name = "ftrgz", type = "float" },
      { name = "faddord", type = "bool" },
      { name = "fdofirst", type = "bool" },
      { name = "frebuild", type = "bool" },
      { name = "fcenter", type = "bool" },
      { name = "fmode", type = "int" },
      { name = "fgroup", type = "int" },
      { name = "fplayer", type = "int" },
      { name = "fcid", type = "int" },
      { name = "fracename", type = "string" },
      { name = "fbasename", type = "string" },
      { name = "fhandle", type = "int" },
      { name = "fcapture", type = "bool" },
      { name = "fordtyp", type = "int" },
      { name = "ftarget", type = "int" },
      { name = "fclrord", type = "bool" },
      { name = "fintlst", type = "Pointer" },
      { name = "famount", type = "int" },
      { name = "fbstate", type = "bool" },
      { name = "fform", type = "int" },
      { name = "fsquad", type = "int" },
      { name = "fofficer", type = "int" },
      { name = "fdrummer", type = "int" },
      { name = "fposition", type = "bool" },
      { name = "flocktrg", type = "bool" },
      { name = "fsid", type = "string" },
      { name = "find", type = "int" },
      { name = "fresult", type = "int" },
      { name = "fdead", type = "bool" },
      { name = "fweaponid", type = "int" },
      { name = "frnd", type = "float" },
      { name = "fbyte0", type = "Byte" },
      { name = "fbyte1", type = "Byte" },
      { name = "fbyte2", type = "Byte" },
      { name = "fpointer0", type = "Pointer" },
      { name = "fpointer1", type = "Pointer" },
    },
    TPlayerCounters = {
      { name = "total", type = "int" },
      { name = "farmused", type = "int" },
      { name = "scores", type = "int" },
      { name = "idlepeasants", type = "int" },
      { name = "idlemines", type = "int" },
      { name = "resconsume", array = { 0, 6 }, of = { type = "int" } },
      { name = "resconsumeremains", array = { 0, 6 }, of = { type = "int" } },
      { name = "resincome", array = { 0, 6 }, of = { type = "int" } },
      { name = "resincomeremains", array = { 0, 6 }, of = { type = "int" } },
      { name = "workersonres", array = { 0, 6 }, of = { type = "int" } },
      { name = "all", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
      { name = "built", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
    },
    TPlayerLists = {
      { name = "buildings", type = "TIntegerList" },
      { name = "storehouses", type = "TIntegerList" },
      { name = "ports", type = "TIntegerList" },
      { name = "deluids", type = "TIntegerList" },
    },
    TPlayerStatistics = {
      { name = "restotal", array = { 0, 6 }, of = { type = "int" } },
      { name = "resonupgrade", array = { 0, 6 }, of = { type = "int" } },
      { name = "resonmines", array = { 0, 6 }, of = { type = "int" } },
      { name = "resonunits", array = { 0, 6 }, of = { type = "int" } },
      { name = "resonbuildings", array = { 0, 6 }, of = { type = "int" } },
      { name = "resonlife", array = { 0, 6 }, of = { type = "int" } },
      { name = "resbuy", array = { 0, 6 }, of = { type = "int" } },
      { name = "ressell", array = { 0, 6 }, of = { type = "int" } },
      { name = "killed", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
      { name = "produced", array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "int" } } },
      { name = "population", type = "TIntegerList" },
      { name = "scores", type = "TIntegerList" },
    },
    TPlayerUpgradeState = {
      { name = "sid", type = "string" },
      { name = "done", type = "bool" },
      { name = "enabled", type = "bool" },
      { name = "inprogress", type = "bool" },
      { name = "grey", type = "bool" },
      { name = "timestart", type = "float" },
      { name = "timedone", type = "float" },
      { name = "bscenariodisabled", type = "bool" },
    },
    TPos2f = {
      { name = "x", type = "Float = 0" },
      { name = "y", type = "Float = 0" },
    },
    TPos3f = {
      { name = "x", type = "Float = 0" },
      { name = "y", type = "Float = 0" },
      { name = "z", type = "Float = 0" },
    },
    TProfile = {
      { name = "name", type = "string" },
      { name = "sndmute", type = "int" },
      { name = "sndmaster", type = "float" },
      { name = "sndmusic", type = "float" },
      { name = "sndambient", type = "float" },
      { name = "sndfx", type = "float" },
      { name = "sndvoice", type = "float" },
      { name = "sndinterface", type = "float" },
      { name = "keyscrollspeed", type = "float" },
      { name = "mousescrollspeed", type = "float" },
      { name = "middlemousescrollspeed", type = "float" },
      { name = "wheelspeed", type = "float" },
      { name = "igamespeed", type = "int" },
      { name = "lastcampaignsave", type = "string" },
      { name = "lastcustomsave", type = "string" },
      { name = "netemail", type = "string" },
      { name = "netpass", type = "string" },
      { name = "netcdkey", type = "string" },
      { name = "bautosave", type = "bool" },
      { name = "bbrushunderunit", type = "bool" },
      { name = "bclipmouse", type = "bool" },
      { name = "bsearchenemyinfront", type = "bool" },
      { name = "binfiniteonleftclick", type = "bool" },
      { name = "bselectallunitsonz", type = "bool" },
      { name = "bfreezoom", type = "bool" },
      { name = "bDbgPreloadPatterns", type = "bool" },
      { name = "bDbgLogPointerNil", type = "bool" },
      { name = "bDbgVisualizePlayOnceProjFX", type = "bool" },
      { name = "bShowPause", type = "bool" },
      { name = "bShowMiniMap", type = "bool" },
      { name = "bcenterfirstrow", type = "bool" },
      { name = "bFamine", type = "bool" },
      { name = "bRestrictCamera", type = "bool" },
      { name = "bDbgCamera", type = "bool" },
      { name = "bDbgNoBrushes", type = "bool" },
      { name = "bDbgHotkeys", type = "bool" },
      { name = "bDbgUnitDebugInfo", type = "bool" },
      { name = "bDemo", type = "bool" },
      { name = "bNewMapOnMainMenu", type = "bool" },
      { name = "bCheatPlaceUnits", type = "bool" },
      { name = "bCheatNoFogOfWar", type = "bool" },
      { name = "bCheatSwitchPlayer", type = "bool" },
      { name = "bCheatPeaceMode", type = "bool" },
      { name = "bCheatNoSpeedLimit", type = "bool" },
      { name = "bCheatCopyPaste", type = "bool" },
      { name = "bCheatMoveUnits", type = "bool" },
      { name = "bCheatShowAllMissions", type = "bool" },
      { name = "bShowFPS", type = "bool" },
      { name = "bNoAchs", type = "bool" },
      { name = "bDevMode", type = "bool" },
      { name = "lang", type = "string" },
      { name = "displaymode", type = "string" },
      { name = "dontshowannouncement", type = "int" },
      { name = "lastknowndlcs", type = "int" },
      { name = "purchaseunixtime", type = "int" },
    },
    TProfileUserStruct = {
      { name = "custommap", type = "TMap" },
      { name = "campaign", type = "TUserCampaign" },
      { name = "achs", type = "TAchs" },
      { name = "adviserdefault", type = "TAdviser" },
    },
    TProgress = {
      { name = "lastprogresstime", type = "float" },
      { name = "progresstick", type = "int" },
      { name = "soundlastprogresstime", type = "float" },
      { name = "soundprogresstick", type = "int" },
      { name = "soundcounterlastprogresstime", type = "float" },
      { name = "soundcounterprogresstick", type = "int" },
      { name = "lastprogresshistorytime", type = "float" },
      { name = "lastmiscplsecmaxtime", type = "float" },
      { name = "lastpoolplsecmaxtime", type = "float" },
      { name = "lastsearchenemycountmidtime", type = "float" },
      { name = "lastsearchenemycountsumtime", type = "float" },
      { name = "lastsearchenemycountertime", type = "float" },
      { name = "lastprogressstatisticstime", type = "float" },
      { name = "lastprogresstopzonestime", type = "float" },
      { name = "lastupdateenemyticktime", type = "float" },
      { name = "lastupdateenemytickteam", type = "int" },
      { name = "lastsoundprogressfreqtime", array = { 0, 5 }, of = { type = "float" } },
      { name = "lastsoundprogresscounterfreqtime", array = { 0, 5 }, of = { type = "float" } },
      { name = "lastupdateenemyinfotime", type = "float" },
    },
    TProj = {
      { name = "baseid", type = "int" },
      { name = "weaponid", type = "int" },
      { name = "owner", type = "int" },
      { name = "trg", type = "int" },
      { name = "px", type = "float" },
      { name = "py", type = "float" },
      { name = "pz", type = "float" },
      { name = "dx", type = "float" },
      { name = "dy", type = "float" },
      { name = "dz", type = "float" },
      { name = "ownercid", type = "int" },
      { name = "ownerid", type = "int" },
      { name = "ownerweaponind", type = "int" },
      { name = "uniqrnd", type = "float" },
    },
    TProjSimulatePoint = {
      { name = "weaponid", type = "int" },
      { name = "owner", type = "int" },
      { name = "px", type = "float" },
      { name = "pz", type = "float" },
      { name = "damagetime", type = "float" },
    },
    TProjSimulatePoints = {
      { name = "curind", type = "int" },
      { name = "maxdamagetime", type = "float" },
      { name = "projsim", array = { 0, 2047 }, of = { type = "TProjSimulatePoint" } },
    },
    TPtrList = {
      { name = "fCount", type = "int" },
      { name = "fCapacity", type = "int" },
      { name = "fGrowthDelta", type = "int" },
      { name = "fBufferItem", type = "Pointer" },
      { name = "fPackMode", type = "bool" },
      { name = "fDebug", type = "bool" },
      { name = "fExternalMemory", type = "bool" },
      { name = "fResetsMemory", type = "bool" },
      { name = "fBaseList", type = "Pointer" },
      { name = "fItemSize", type = "int" },
    },
    TQuickPlayer = {
      { name = "playerid", type = "int" },
      { name = "sessionid", type = "int" },
      { name = "weight", type = "float" },
      { name = "score", type = "int" },
      { name = "rank", type = "float" },
      { name = "games", type = "int" },
      { name = "wins", type = "int" },
      { name = "waittime", type = "float" },
      { name = "ram", type = "int" },
      { name = "tolerance", type = "float" },
      { name = "winrate", type = "float" },
      { name = "checksum", type = "string" },
    },
    TQuickPlayers = {
      { name = "player", array = { 0, nil }, of = { type = "TQuickPlayer" } },
      { name = "count", type = "int" },
      { name = "session", array = { 0, nil }, of = { type = "TQuickSession" } },
      { name = "sessioncount", type = "int" },
      { name = "sessionplayercount", type = "int" },
    },
    TQuickSession = {
      { name = "players", array = { 0, 10 }, of = { type = "TQuickPlayer" } },
    },
    TReconnectManager = {
      { name = "bsessionstarted", type = "bool" },
      { name = "btryreconnect", type = "bool" },
      { name = "bimpossibletoreconnect", type = "bool" },
      { name = "bsuccessreconnectserver", type = "bool" },
      { name = "bsuccessreconnectroom", type = "bool" },
      { name = "bconnectedserver", type = "bool" },
      { name = "bconnectedroom", type = "bool" },
      { name = "sessionstarttime", type = "float" },
      { name = "sessionendtime", type = "float" },
      { name = "attempt", type = "int" },
      { name = "lastattempttime", type = "float" },
      { name = "prevstate", type = "int" },
    },
    TRect = {
      { name = "minx", type = "Float = 0" },
      { name = "miny", type = "Float = 0" },
      { name = "maxx", type = "Float = 0" },
      { name = "maxy", type = "Float = 0" },
    },
    TRes = {
      { name = "baseid", type = "int" },
      { name = "hp", type = "int" },
      { name = "itype", type = "int" },
      { name = "radius", type = "int" },
      { name = "worktransorm", type = "int" },
      { name = "timetransormlast", type = "float" },
      { name = "resgrid", type = "int" },
      { name = "brised", type = "bool" },
    },
    TResGridList = {
      { name = "fCount", type = "int" },
      { name = "fCapacity", type = "int" },
      { name = "fGrowthDelta", type = "int" },
      { name = "fBufferItem", type = "Pointer" },
      { name = "fPackMode", type = "bool" },
      { name = "fExternalMemory", type = "bool" },
      { name = "fResetsMemory", type = "bool" },
      { name = "fBaseList", type = "Pointer" },
      { name = "fItemSize", type = "int" },
      { name = "fResCount", array = { 0, 6 }, of = { type = "int" } },
      { name = "fWorkerCount", array = { 0, 11 }, of = { array = { 0, 6 }, of = { type = "int" } } },
    },
    TScenario = {
      { name = "bactive", type = "bool" },
      { name = "bexists", type = "bool" },
      { name = "campname", type = "string" },
      { name = "missname", type = "string" },
      { name = "difficulty", type = "int" },
      { name = "settings", type = "TScenarioSettings" },
      { name = "ui", type = "TScenarioUI" },
      { name = "players", array = { 0, 11 }, of = { type = "TScenarioPlayer" } },
      { name = "flags", array = { 0, nil }, of = { type = "TScenarioFlag" } },
      { name = "counters", array = { 0, nil }, of = { type = "TScenarioCounter" } },
      { name = "timers", array = { 0, nil }, of = { type = "TScenarioTimer" } },
      { name = "groups", array = { 0, nil }, of = { type = "TScenarioGroup" } },
      { name = "zones", array = { 0, nil }, of = { type = "TScenarioZone" } },
      { name = "triggers", array = { 0, nil }, of = { type = "TScenarioTrigger" } },
      { name = "objectives", array = { 0, nil }, of = { type = "TScenarioObjective" } },
      { name = "queries", array = { 0, nil }, of = { type = "TScenarioQuery" } },
      { name = "images", array = { 0, nil }, of = { type = "TScenarioImage" } },
      { name = "results", array = { 0, nil }, of = { type = "TScenarioResult" } },
      { name = "resulttriggers", array = { 0, nil }, of = { type = "TScenarioTrigger" } },
    },
    TScenarioCounter = {
      { name = "name", type = "string" },
      { name = "value", type = "int" },
    },
    TScenarioFlag = {
      { name = "name", type = "string" },
      { name = "bactive", type = "bool" },
    },
    TScenarioGroup = {
      { name = "name", type = "string" },
      { name = "unitslist", type = "TIntegerList" },
    },
    TScenarioImage = {
      { name = "name", type = "string" },
      { name = "material", type = "string" },
    },
    TScenarioObjective = {
      { name = "name", type = "string" },
      { name = "langtable", type = "string" },
      { name = "langkey", type = "string" },
      { name = "gametime", type = "float" },
      { name = "bvisible", type = "bool" },
      { name = "bdone", type = "bool" },
    },
    TScenarioPlayer = {
      { name = "name", type = "string" },
      { name = "cid", type = "int" },
      { name = "team", type = "int" },
      { name = "difficulty", type = "int" },
      { name = "resources", array = { 0, 6 }, of = { type = "int" } },
      { name = "bai", type = "bool" },
    },
    TScenarioQuery = {
      { name = "name", type = "string" },
      { name = "langtable", type = "string" },
      { name = "langkey", type = "string" },
      { name = "imageid", type = "int" },
      { name = "results", array = { 0, nil }, of = { type = "int" } },
    },
    TScenarioResult = {
      { name = "name", type = "string" },
      { name = "langtable", type = "string" },
      { name = "langkey", type = "string" },
      { name = "nextqueryid", type = "int" },
      { name = "resulttriggerid", type = "int" },
      { name = "executecount", type = "int" },
    },
    TScenarioSettings = {
      { name = "filename", type = "string" },
      { name = "preview", type = "string" },
      { name = "langfilename", type = "string" },
      { name = "langtable", type = "string" },
      { name = "name", type = "string" },
      { name = "description", type = "string" },
    },
    TScenarioTimer = {
      { name = "name", type = "string" },
      { name = "bstarted", type = "bool" },
      { name = "bfinished", type = "bool" },
      { name = "time", type = "float" },
      { name = "starttime", type = "float" },
    },
    TScenarioTrigger = {
      { name = "name", type = "string" },
      { name = "bactive", type = "bool" },
      { name = "bexists", type = "bool" },
      { name = "btriggertreeopen", type = "bool" },
      { name = "bconditionstreeopen", type = "bool" },
      { name = "bactionstreeopen", type = "bool" },
      { name = "conditions", array = { 0, nil }, of = { type = "TScenarioTriggerCondition" } },
      { name = "actions", array = { 0, nil }, of = { type = "TScenarioTriggerAction" } },
      { name = "activetime", type = "float" },
    },
    TScenarioTriggerAction = {
      { name = "id", type = "int" },
      { name = "triggerid", type = "int" },
      { name = "flagid", type = "int" },
      { name = "counterid", type = "int" },
      { name = "timerid", type = "int" },
      { name = "groupid", type = "int" },
      { name = "groupidtrg", type = "int" },
      { name = "zoneid", type = "int" },
      { name = "objectiveid", type = "int" },
      { name = "queryid", type = "int" },
      { name = "bactive", type = "bool" },
      { name = "bstate", type = "bool" },
      { name = "usecounterid", type = "int" },
      { name = "busecounterasamount", type = "bool" },
      { name = "busecounterastime", type = "bool" },
      { name = "player", type = "int" },
      { name = "playertrg", type = "int" },
      { name = "resource", type = "int" },
      { name = "amount", type = "int" },
      { name = "time", type = "float" },
      { name = "radius", type = "float" },
      { name = "countryid", type = "int" },
      { name = "unitid", type = "int" },
      { name = "direction", type = "float" },
      { name = "upgradeid", type = "int" },
      { name = "formationid", type = "int" },
      { name = "executestate", type = "string" },
      { name = "stringregister", type = "string" },
      { name = "marker", type = "int" },
    },
    TScenarioTriggerCondition = {
      { name = "id", type = "int" },
      { name = "triggerid", type = "int" },
      { name = "flagid", type = "int" },
      { name = "counterid", type = "int" },
      { name = "timerid", type = "int" },
      { name = "groupid", type = "int" },
      { name = "zoneid", type = "int" },
      { name = "resultid", type = "int" },
      { name = "bactive", type = "bool" },
      { name = "bstate", type = "bool" },
      { name = "usecounterid", type = "int" },
      { name = "busecounterasamount", type = "bool" },
      { name = "busecounterastime", type = "bool" },
      { name = "player", type = "int" },
      { name = "difficulty", type = "int" },
      { name = "resource", type = "int" },
      { name = "amount", type = "int" },
      { name = "sign", type = "int" },
      { name = "time", type = "float" },
      { name = "executestate", type = "string" },
      { name = "stringregister", type = "string" },
    },
    TScenarioUI = {
      { name = "helpertype", type = "int" },
      { name = "bshowui", type = "bool" },
      { name = "beditresulttrigger", type = "bool" },
      { name = "pickedtriggerindex", type = "int" },
      { name = "pickedconditionindex", type = "int" },
      { name = "pickedactionindex", type = "int" },
      { name = "pickedplayerindex", type = "int" },
      { name = "pickedflagindex", type = "int" },
      { name = "pickedcounterindex", type = "int" },
      { name = "pickedtimerindex", type = "int" },
      { name = "pickedgroupindex", type = "int" },
      { name = "pickedzoneindex", type = "int" },
      { name = "pickedobjectiveindex", type = "int" },
      { name = "pickedqueryindex", type = "int" },
      { name = "pickedimageindex", type = "int" },
      { name = "pickedresultindex", type = "int" },
      { name = "pickedresulttriggerindex", type = "int" },
      { name = "pickedresulttriggeractionindex", type = "int" },
      { name = "pickedresulttriggerconditionindex", type = "int" },
      { name = "copytriggercache", type = "TScenarioTrigger" },
      { name = "copyactioncache", type = "TScenarioTriggerAction" },
      { name = "copyconditioncache", type = "TScenarioTriggerCondition" },
    },
    TScenarioZone = {
      { name = "name", type = "string" },
      { name = "x", type = "float" },
      { name = "y", type = "float" },
      { name = "w", type = "float" },
      { name = "h", type = "float" },
      { name = "bactive", type = "bool" },
      { name = "player", type = "int" },
      { name = "group", type = "int" },
      { name = "blinkgroup", type = "bool" },
      { name = "buseaverage", type = "bool" },
      { name = "addradius", type = "float" },
      { name = "linkgroup", type = "int" },
      { name = "bonlyungroup", type = "bool" },
      { name = "unitslist", type = "TIntegerList" },
    },
    TSelection = {
      { name = "id", type = "int" },
      { name = "count", type = "int" },
      { name = "hp", type = "int" },
      { name = "maxhp", type = "int" },
      { name = "bshiftsel", type = "bool" },
      { name = "bbuiltexists", type = "bool" },
    },
    TSelectionSquad = {
      { name = "squad", type = "int" },
      { name = "count", type = "int" },
      { name = "hp", type = "int" },
      { name = "maxhp", type = "int" },
      { name = "bshiftsel", type = "bool" },
    },
    TSettings = {
      { name = "video", type = "TSettingsVideo" },
    },
    TSettingsVideo = {
      { name = "preset", type = "string" },
      { name = "resolution", type = "int" },
      { name = "antialiasing", type = "string" },
      { name = "fxaa", type = "bool" },
      { name = "ssao", type = "bool" },
      { name = "hdrtype", type = "string" },
      { name = "vsyncmode", type = "string" },
      { name = "shadowenabled", type = "bool" },
      { name = "shadowmap", type = "string" },
      { name = "texturequality", type = "string" },
      { name = "texturefilter", type = "string" },
      { name = "shadertype", type = "string" },
      { name = "waterreflection", type = "string" },
      { name = "lightpreset", type = "int" },
      { name = "advanced", type = "bool" },
    },
    TSoundGrid = {
      { name = "sndrequests", array = { 0, 88 }, of = { type = "int" } },
      { name = "bsndrequestexist", type = "bool" },
    },
    TSoundManager = {
      { name = "bprocess", type = "bool" },
      { name = "lastprogresstime", type = "float" },
      { name = "emitterhnd", type = "int" },
      { name = "frustumltx", type = "float" },
      { name = "frustumlty", type = "float" },
      { name = "frustumrtx", type = "float" },
      { name = "frustumrty", type = "float" },
      { name = "frustumrbx", type = "float" },
      { name = "frustumrby", type = "float" },
      { name = "frustumlbx", type = "float" },
      { name = "frustumlby", type = "float" },
      { name = "frustumcenx", type = "float" },
      { name = "frustumceny", type = "float" },
      { name = "frustumrad", type = "float" },
      { name = "counter", type = "TSoundManagerCounter" },
    },
    TSoundManagerCounter = {
      { name = "walkinfcloth", type = "int" },
      { name = "walkinfmetal", type = "int" },
      { name = "walkartwheels", type = "int" },
      { name = "walkartmortar", type = "int" },
      { name = "walkcavfast", type = "int" },
      { name = "walkcavslow", type = "int" },
      { name = "walkpeastone", type = "int" },
      { name = "walkpea", type = "int" },
      { name = "walkdstinfcloth", type = "float" },
      { name = "walkdstinfmetal", type = "float" },
      { name = "walkdstartwheels", type = "float" },
      { name = "walkdstartmortar", type = "float" },
      { name = "walkdstcavfast", type = "float" },
      { name = "walkdstcavslow", type = "float" },
      { name = "walkdstpeastone", type = "float" },
      { name = "walkdstpea", type = "float" },
    },
    TSquad = {
      { name = "fList", type = "TIntegerList" },
      { name = "fFormation", type = "int" },
      { name = "fBaseCount", type = "int" },
      { name = "fStandGround", type = "bool" },
      { name = "fSearchVictim", type = "bool" },
      { name = "fSelected", type = "bool" },
      { name = "fIndex", type = "int" },
      { name = "fOfficerID", type = "int" },
      { name = "fPlIndex", type = "int" },
      { name = "fGroupName", type = "string" },
      { name = "fHoldMode", type = "bool" },
      { name = "fAddDamage", type = "int" },
      { name = "fAddShield", type = "int" },
      { name = "fAddDamageHold", type = "int" },
      { name = "fAddShieldHold", type = "int" },
      { name = "fDirX", type = "float" },
      { name = "fDirZ", type = "float" },
      { name = "fWidth", type = "int" },
      { name = "fHeight", type = "int" },
      { name = "fMoveCount", type = "int" },
      { name = "fAttackCount", type = "int" },
      { name = "fDelayCount", type = "int" },
      { name = "fUID", type = "int" },
      { name = "fTag", type = "float" },
      { name = "fAgressive", type = "bool" },
      { name = "fAttackMode", type = "bool" },
      { name = "fHoldModeProgress", type = "float" },
      { name = "fNeedRebuild", type = "bool" },
      { name = "fCurX", type = "float" },
      { name = "fCurZ", type = "float" },
      { name = "fArmy", type = "int" },
      { name = "fType", type = "int" },
      { name = "fWarType", type = "int" },
      { name = "arGrid", array = { 0, 24 }, of = { array = { 0, 54 }, of = { type = "int" } } },
    },
    TSquadList = {
      { name = "fList", type = "TPtrList" },
      { name = "fNextUID", type = "int" },
    },
    TTopZone = {
      { name = "danger", array = { 0, 12 }, of = { type = "float" } },
      { name = "attract", array = { 0, 12 }, of = { type = "float" } },
      { name = "changeDanger", array = { 0, 12 }, of = { type = "float" } },
      { name = "changeAttract", array = { 0, 12 }, of = { type = "float" } },
      { name = "centerDist", array = { 0, 12 }, of = { type = "int" } },
      { name = "changed", type = "bool" },
    },
    TTower = {
      { name = "hnd", type = "int" },
      { name = "pause", type = "float" },
      { name = "radius", type = "float" },
      { name = "update", type = "bool" },
      { name = "remove", type = "bool" },
    },
    TTowerList = {
      { name = "fList", type = "TPtrList" },
    },
    TUIConst = {
      { name = "halign", array = { 0, nil }, of = { type = "string" } },
      { name = "valign", array = { 0, nil }, of = { type = "string" } },
      { name = "font", array = { 0, nil }, of = { type = "string" } },
      { name = "fontstyle", array = { 0, nil }, of = { type = "string" } },
    },
    TUniqUpgList = {
      { name = "fList", type = "TPtrList" },
    },
    TUniqUpgrade = {
      { name = "cid", type = "int" },
      { name = "unitid", type = "int" },
      { name = "airole", type = "int" },
      { name = "levelid", array = { 0, 7 }, of = { type = "int" } },
      { name = "levelsid", array = { 0, 7 }, of = { type = "string" } },
    },
    TUnitUpgrade = {
      { name = "unitid", type = "int" },
      { name = "defenceupgrade", type = "int" },
      { name = "attackupgrade", type = "int" },
      { name = "defenceupgradeid", array = { 0, 7 }, of = { type = "int" } },
      { name = "attackupgradeid", array = { 0, 7 }, of = { type = "int" } },
    },
    TUserCampaign = {
      { name = "difficulty", type = "int" },
      { name = "campprogress", array = { 0, 255 }, of = { type = "TCampaignProgress" } },
    },
    TVec3f = {
      { name = "x", type = "Float = 0" },
      { name = "y", type = "Float = 0" },
      { name = "z", type = "Float = 0" },
    },
    TWallCell = {
      { name = "fSprite", type = "int" },
      { name = "x", type = "int" },
      { name = "y", type = "int" },
      { name = "wallType", type = "int" },
      { name = "cid", type = "int" },
      { name = "visible", type = "bool" },
      { name = "goHnd", type = "int" },
      { name = "plInd", type = "int" },
    },
    TWallCluster = {
      { name = "wallType", type = "int" },
      { name = "cornPt", type = "TIntegerList" },
      { name = "Cells", type = "TPtrList" },
      { name = "lastX", type = "int" },
      { name = "lastY", type = "int" },
      { name = "finalX", type = "int" },
      { name = "finalY", type = "int" },
      { name = "plIndex", type = "int" },
      { name = "cid", type = "int" },
      { name = "firstWall", type = "bool" },
      { name = "buildWall", type = "bool" },
    },
    TWallSystem = {
      { name = "fList", type = "TPtrList" },
    },
    TWeapon = {
      { name = "sid", type = "string" },
      { name = "id", type = "int" },
      { name = "fx", type = "string" },
      { name = "projbasename", type = "string" },
      { name = "damage", type = "int" },
      { name = "radius", type = "float" },
      { name = "gravity", type = "float" },
      { name = "angle", type = "float" },
      { name = "speed", type = "float" },
      { name = "propagation", type = "int" },
      { name = "time", type = "float" },
      { name = "trailfx", type = "string" },
      { name = "sound", type = "string" },
      { name = "sndind", type = "int" },
      { name = "buseownerdamage", type = "bool" },
      { name = "buseownerfxshot", type = "bool" },
      { name = "buseownercustomobjpoints", type = "bool" },
      { name = "brotate", type = "bool" },
      { name = "bcollisiondetection", type = "bool" },
      { name = "bcheckfriendonline", type = "bool" },
      { name = "volumeclippedfreq", type = "float" },
      { name = "expdecname", type = "string" },
      { name = "childs", type = "TWeaponChild" },
      { name = "customexplosions", array = { 0, 6 }, of = { type = "TWeaponCustomExplosion" } },
      { name = "syncweaponslist", type = "TIntegerList" },
    },
    TWeaponChild = {
      { name = "mincount", type = "int" },
      { name = "maxcount", type = "int" },
      { name = "buseparentdestpos", type = "bool" },
      { name = "list", type = "TIntegerList" },
    },
    TWeaponCustomExplosion = {
      { name = "mincount", type = "int" },
      { name = "maxcount", type = "int" },
      { name = "list", type = "TIntegerList" },
    },
    TWriteNewRequest = {
      { name = "plind", type = "int" },
      { name = "racename", type = "string" },
      { name = "basename", type = "string" },
      { name = "cid", type = "int" },
      { name = "uid", type = "int" },
      { name = "posx", type = "float" },
      { name = "posz", type = "float" },
      { name = "itype", type = "int" },
      { name = "bpush", type = "bool" },
    },
  },
  globals = {
    WallDx8 = { array = { 0, 8 }, of = { type = "int" } },
    WallDy8 = { array = { 0, 8 }, of = { type = "int" } },
    WallGd8 = { array = { 0, 9 }, of = { type = "int" } },
    gAIConst = { type = "TAIConst" },
    gAchLastUpgrades = { type = "TIntegerList" },
    gArcherGrid = { array = { 0, 19 }, of = { array = { 0, 19 }, of = { type = "TArcherCell" } } },
    gArmyInfoCells = { array = { 0, nil }, of = { array = { 0, nil }, of = { type = "TArmyInfoCell" } } },
    gCanPlaceBuildingWalls = { array = { 0, 639 }, of = { array = { 0, 639 }, of = { type = "TCanPlaceBuildingWalls" } } },
    gChatLog = { array = { 0, 255 }, of = { type = "string" } },
    gChatMessages = { type = "TChatMessages" },
    gConnectHost = { type = "string" },
    gConnectIPCount = { type = "int" },
    gConnectIPIndex = { type = "int" },
    gConnectIPList = { array = { 0, 9 }, of = { type = "string" } },
    gConnectLoginState = { type = "int" },
    gConnectModal = { type = "int" },
    gConnectState = { type = "int" },
    gConnectTimer = { type = "float" },
    gConst = { type = "TConst" },
    gConstScenarioMarkers = { array = { 0, nil }, of = { type = "string" } },
    gCountry = { array = { 0, 23 }, of = { type = "TCountry" } },
    gCtrlGroups = { array = { 0, 11 }, of = { array = { 0, 9 }, of = { type = "TIntegerList" } } },
    gCustomBuildPointsWall = { array = { 0, 23 }, of = { type = "TCustomBuildPointsWall" } },
    gCustomObjPoints = { array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "TCustomObjPoints" } } },
    gDbgObj = { type = "TObj" },
    gDeathUnits = { type = "TIntegerList" },
    gDestructListBuilding = { type = "TIntegerList" },
    gDestructListShip = { type = "TIntegerList" },
    gDoRoundDamageList = { type = "TIntegerList" },
    gEconomy = { array = { 0, 6 }, of = { type = "TEconomy" } },
    gEmptyList = { type = "TIntegerList" },
    gEnemyInfoList = { type = "TEnemyInfoList" },
    gFloat_test_maxX = { type = "float" },
    gFloat_test_maxY = { type = "float" },
    gFloat_test_minX = { type = "float" },
    gFloat_test_minY = { type = "float" },
    gFonts = { array = { 0, 31 }, of = { type = "TFonts" } },
    gFormation = { array = { 0, 159 }, of = { type = "TFormation" } },
    gGOPathList = { type = "TIntegerList" },
    gGuiSelectionHelper = { type = "TIntegerList" },
    gGuiUpdateHighlights = { type = "TIntegerList" },
    gIdleGrid = { array = { 0, 799 }, of = { array = { 0, 799 }, of = { type = "int" } } },
    gInetEventLock = { type = "int" },
    gIntListWriteSquadAction = { type = "TIntegerList" },
    gInt_MaxTopZoneChanged = { type = "int" },
    gInt_MinTopZoneChanged = { type = "int" },
    gInt_UpdateAreasCount = { type = "int" },
    gIntegerList = { type = "TIntegerList" },
    gInterface = { type = "TInterface" },
    gInternetShell = { type = "TInternetShell" },
    gInternetShellTmp = { type = "TInternetShell" },
    gIslands = { type = "TIslands" },
    gKeyColor = { array = { 0, 23 }, of = { array = { 0, 2 }, of = { type = "float" } } },
    gLanGameMode = { type = "int" },
    gLanHostID = { type = "int" },
    gLanMyID = { type = "int" },
    gLanRecreate = { type = "TLanRecreate" },
    gLanSyncData = { type = "TLanSyncData" },
    gLanSyncDataLast = { type = "TLanSyncData" },
    gLanSyncUnitsParamsUIDList = { type = "TIntegerList" },
    gLogMessages = { type = "TLogMessages" },
    gMap = { type = "TMap" },
    gMapHistoricalBattle = { type = "TMap" },
    gMapMask = { array = { 0, 639 }, of = { array = { 0, 639 }, of = { type = "TGeneratorBitmapMask" } } },
    gMapTerrainData = { type = "TMapTerrainData" },
    gObjProp = { array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "TObjProp" } } },
    gOrderUnitsList = { type = "TIntegerList" },
    gOrderUnitsListTmp = { type = "TIntegerList" },
    gPathTag = { type = "int", bytes = 1 },
    gPatternMask = { array = { 0, 639 }, of = { array = { 0, 639 }, of = { type = "bool" } } },
    gPlayer = { array = { 0, 11 }, of = { type = "TPlayer" } },
    gPrevRealTime = { type = "float" },
    gPrimitives = { type = "TIntegerList" },
    gProfile = { type = "TProfile" },
    gProfileTmp = { type = "TProfile" },
    gProfileUserStruct = { type = "TProfileUserStruct" },
    gProfileUserStructTmp = { type = "TProfileUserStruct" },
    gProgress = { type = "TProgress" },
    gProjSimulatePoints = { type = "TProjSimulatePoints" },
    gPtrList = { type = "TPtrList" },
    gQuickPlay = { type = "TQuickPlayers" },
    gQuickPlayHideIcon = { type = "TIntegerList" },
    gRealTimeProcessed = { type = "float" },
    gReconnectManager = { type = "TReconnectManager" },
    gRecordGeneratorVersion = { type = "int" },
    gRegionsList = { type = "TIntegerList" },
    gRepairSessionList = { type = "TIntegerList" },
    gResGrid = { array = { 0, nil }, of = { array = { 0, nil }, of = { type = "TResGridList" } } },
    gSVNVersion = { type = "int" },
    gScanGrid = { array = { 0, nil }, of = { array = { 0, nil }, of = { type = "TGridList" } } },
    gScanGridUnits = { array = { 0, 11 }, of = { array = { 0, nil }, of = { array = { 0, nil }, of = { type = "TIntegerList" } } } },
    gScenario = { type = "TScenario" },
    gScenarioTmp = { type = "TScenario" },
    gSelectedObjects = { type = "TIntegerList" },
    gSelectedSquads = { type = "TPtrList" },
    gSelection = { array = { 0, 23 }, of = { array = { 0, 79 }, of = { type = "TSelection" } } },
    gSelectionSquads = { array = { 0, 499 }, of = { type = "TSelectionSquad" } },
    gSettings = { type = "TSettings" },
    gSettingsTmp = { type = "TSettings" },
    gShellSortOnline = { type = "TIntegerList" },
    gShellSortOnlineMarked = { type = "TIntegerList" },
    gShellSortPlay = { type = "TIntegerList" },
    gShellSortPlayMarked = { type = "TIntegerList" },
    gSoundGrid = { array = { 0, nil }, of = { array = { 0, nil }, of = { type = "TSoundGrid" } } },
    gSoundManager = { type = "TSoundManager" },
    gSyncRes = { type = "TIntegerList" },
    gTmpHotkeyArray = { array = { 0, 63 }, of = { array = { 0, 3 }, of = { type = "string" } } },
    gTmpIntList = { type = "TIntegerList" },
    gTmpIntListFillSquad = { type = "TIntegerList" },
    gTmpIntListFindUnits = { type = "TIntegerList" },
    gTmpIntListGUIDrummerList = { type = "TIntegerList" },
    gTmpIntListGUIInsideList = { type = "TIntegerList" },
    gTmpIntListGUISquadList = { type = "TIntegerList" },
    gTmpIntListGetBuildPoints = { type = "TIntegerList" },
    gTmpIntListLANSquadTimeList = { type = "TIntegerList" },
    gTmpIntListLANSquadUIDList = { type = "TIntegerList" },
    gTmpIntListMembers = { type = "TIntegerList" },
    gTmpIntListObjectsInRadius = { type = "TIntegerList" },
    gTmpIntListOnSelection = { type = "TIntegerList" },
    gTmpIntListUpgrades = { type = "TIntegerList" },
    gUIConst = { type = "TUIConst" },
    gUnderCursorList = { type = "TIntegerList" },
    gUpdateAreas = { array = { 0, 499 }, of = { type = "TRect" } },
    gWallCluster = { type = "TWallCluster" },
    gWallClusterCreate = { type = "TWallCluster" },
    gWallSystem = { type = "TWallSystem" },
    gWaterPathList = { type = "TIntegerList" },
    gWeapons = { array = { 0, 255 }, of = { type = "TWeapon" } },
    gWriteNewRequestList = { type = "TPtrList" },
    gWriteSquadPtrList = { type = "TPtrList" },
    garr_BuildingsAll = { array = { 0, 127 }, of = { type = "string" } },
    garr_BuildingsTowerWall = { array = { 0, 127 }, of = { type = "string" } },
    garr_ShipsCannon = { array = { 0, 127 }, of = { type = "string" } },
    garr_Temporary = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsAll = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsArmored = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsArtillery = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsBayonet = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsCavalry = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsCavalryMelee = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsShooters = { array = { 0, 127 }, of = { type = "string" } },
    garr_UnitsShooters18 = { array = { 0, 127 }, of = { type = "string" } },
    garr_res_dlt = { array = { 0, 6 }, of = { type = "int" } },
    garr_res_trg = { array = { 0, 6 }, of = { type = "int" } },
    garrfloat_perf_progress = { array = { 0, 7 }, of = { type = "float" } },
    gbool_editor_fogofwar = { type = "bool" },
    gbool_editor_peacemode = { type = "bool" },
    gbool_editor_placeunits = { type = "bool" },
    gbool_editor_placeunitsmaximized = { type = "bool" },
    gbool_gui_achupdated = { type = "bool" },
    gbool_gui_attackpointmode = { type = "bool" },
    gbool_gui_bagpiperselected = { type = "bool" },
    gbool_gui_bhistoricalbattle = { type = "bool" },
    gbool_gui_bspectator = { type = "bool" },
    gbool_gui_debug = { type = "bool" },
    gbool_gui_doalarm = { type = "bool" },
    gbool_gui_donewgamerestart = { type = "bool" },
    gbool_gui_drummerselected = { type = "bool" },
    gbool_gui_firstdocreate = { type = "bool" },
    gbool_gui_firstonresize = { type = "bool" },
    gbool_gui_gatefinished = { type = "bool" },
    gbool_gui_goinattackmode = { type = "bool" },
    gbool_gui_guardmode = { type = "bool" },
    gbool_gui_hidenicks = { type = "bool" },
    gbool_gui_ignoreonshortcut = { type = "bool" },
    gbool_gui_isfileexists_campaigns = { type = "bool" },
    gbool_gui_isfileexists_checked_campaigns = { type = "bool" },
    gbool_gui_isselectionstarted = { type = "bool" },
    gbool_gui_keephint = { type = "bool" },
    gbool_gui_landoreadysent = { type = "bool" },
    gbool_gui_mapgenerationfinished = { type = "bool" },
    gbool_gui_maxcameradist = { type = "bool" },
    gbool_gui_newmapfinished = { type = "bool" },
    gbool_gui_newsgoggalaxychecked = { type = "bool" },
    gbool_gui_newsgoggalaxyexists = { type = "bool" },
    gbool_gui_newspanelscroll = { type = "bool" },
    gbool_gui_officerselected = { type = "bool" },
    gbool_gui_onlinedoreadysent = { type = "bool" },
    gbool_gui_outofmemoryrecordclean = { type = "bool" },
    gbool_gui_patrolmode = { type = "bool" },
    gbool_gui_pausestate = { type = "bool" },
    gbool_gui_peasantselected = { type = "bool" },
    gbool_gui_progressoneventflag = { type = "bool" },
    gbool_gui_querywindow = { type = "bool" },
    gbool_gui_quicksave = { type = "bool" },
    gbool_gui_recheckadviseradvice = { type = "bool" },
    gbool_gui_refreshcurrentsession = { type = "bool" },
    gbool_gui_requestshowranking = { type = "bool" },
    gbool_gui_requestsoundonunitcontrol = { type = "bool" },
    gbool_gui_saveresolution = { type = "bool" },
    gbool_gui_saving = { type = "bool" },
    gbool_gui_screenshotcamera = { type = "bool" },
    gbool_gui_sendadviserchangeparser = { type = "bool" },
    gbool_gui_senddatasyncparser = { type = "bool" },
    gbool_gui_setrallypointmode = { type = "bool" },
    gbool_gui_setshellchatinputfocused = { type = "bool" },
    gbool_gui_shellupdatetoplist = { type = "bool" },
    gbool_gui_shifticonsselection = { type = "bool" },
    gbool_gui_showannouncementclosed = { type = "bool" },
    gbool_gui_showcustomgame = { type = "bool" },
    gbool_gui_showhistoricalbattle = { type = "bool" },
    gbool_gui_showinternetshell = { type = "bool" },
    gbool_gui_tradecomboboxopen = { type = "bool" },
    gbool_gui_update_cursor = { type = "bool" },
    gbool_gui_update_editorinfo = { type = "bool" },
    gbool_gui_update_rallypoints = { type = "bool" },
    gbool_gui_update_unitcontrol = { type = "bool" },
    gbool_gui_update_unitcontrol_skip = { type = "bool" },
    gbool_gui_updateadviser = { type = "bool" },
    gbool_gui_updateadviseradvice = { type = "bool" },
    gbool_gui_updatecurrentsessionname = { type = "bool" },
    gbool_gui_updateprogress_unitcontrol = { type = "bool" },
    gbool_gui_waterselection = { type = "bool" },
    gbool_internetshell_clearchat = { type = "bool" },
    gbool_internetshell_firstappearance = { type = "bool" },
    gbool_internetshell_friendschannel = { type = "bool" },
    gbool_isgog = { type = "bool" },
    gbool_issteam = { type = "bool" },
    gbool_lan_changeprofile = { type = "bool" },
    gbool_lan_debug = { type = "bool" },
    gbool_lan_isonlinecached = { type = "bool" },
    gbool_modsactive = { type = "bool" },
    gbool_modsscript = { type = "bool" },
    gbool_modsyncparserwait = { type = "bool" },
    gbool_net_forcesyncdata = { type = "bool" },
    gbool_net_forcesyncres = { type = "bool" },
    gbool_peacemode = { type = "bool" },
    gbool_prevbtnnewsenabled = { type = "bool" },
    gbool_profiler_enabled = { type = "bool" },
    gbool_progress_usewritenewrequestlist = { type = "bool" },
    gbool_recordwascleared = { type = "bool" },
    gbool_scenario_startneeded = { type = "bool" },
    gbool_unit_isshipdummy = { type = "bool" },
    gbool_use_collision = { type = "bool" },
    gbool_use_nomeleeminradius = { type = "bool" },
    gfloat_dbg_logsoundtime = { type = "float" },
    gfloat_gui_alarmx = { type = "float" },
    gfloat_gui_alarmz = { type = "float" },
    gfloat_gui_interfacescale = { type = "float" },
    gfloat_gui_lanlastaliveevent = { type = "float" },
    gfloat_gui_lanlastaliveeventreceived = { array = { 0, 11 }, of = { type = "float" } },
    gfloat_gui_lanlasteventreceived = { type = "float" },
    gfloat_gui_lanlastgamespeedsyncreceived = { type = "float" },
    gfloat_gui_lanlastgametimesync = { type = "float" },
    gfloat_gui_lanlastgametimesyncreceived = { type = "float" },
    gfloat_gui_lastguisoundtime = { type = "float" },
    gfloat_gui_lasttimemusiccrossfade = { type = "float" },
    gfloat_gui_movearrowx = { type = "float" },
    gfloat_gui_movearrowz = { type = "float" },
    gfloat_gui_movecamerax = { type = "float" },
    gfloat_gui_movecameraz = { type = "float" },
    gfloat_gui_musiclastbattletimeend = { type = "float" },
    gfloat_gui_musiclastbattletimestart = { type = "float" },
    gfloat_gui_musiclastnationaltimeend = { type = "float" },
    gfloat_gui_musiclastnationaltimestart = { type = "float" },
    gfloat_gui_newslastscrollposition = { type = "float" },
    gfloat_gui_onlinedoprogressstart = { type = "float" },
    gfloat_gui_outofmemorylastgametimecheck = { type = "float" },
    gfloat_gui_prevmouseworldcoordx = { type = "float" },
    gfloat_gui_prevmouseworldcoordy = { type = "float" },
    gfloat_gui_prevmouseworldcoordz = { type = "float" },
    gfloat_gui_prevselmousex = { type = "float" },
    gfloat_gui_prevselmousez = { type = "float" },
    gfloat_gui_screenshotcameraangle = { type = "float" },
    gfloat_gui_screenshotcamerafov = { type = "float" },
    gfloat_gui_update_progress_lasttime = { type = "float" },
    gfloat_gui_update_unitcontrol_lasttime = { type = "float" },
    gfloat_gui_videoscreenshottimer = { type = "float" },
    gfloat_lan_lastsyncdatatime = { type = "float" },
    gfloat_lan_lastsyncrestime = { type = "float" },
    gfloat_lan_lastsyncstatstime = { type = "float" },
    gfloat_lan_pingredrawwindowtime = { type = "float" },
    gfloat_lan_quickplayautosearch_addtime = { type = "float" },
    gfloat_modsyncparserwaittime = { type = "float" },
    gfloat_news_delaypoint = { type = "float" },
    gfloat_news_lasttime = { type = "float" },
    gfloat_news_lasttimeloadbar = { type = "float" },
    gfloat_news_loadbarpos = { type = "int" },
    gfloat_peacetime = { type = "float" },
    gfloat_progressspeedfactor_lasttimechange = { type = "float" },
    gfloat_progressspeedfactor_lastvalue = { type = "float" },
    gfloat_searchenemy_mid = { type = "float" },
    gfloat_searchenemygridcachetime = { type = "float" },
    gfloat_time_pause = { type = "float" },
    gflt_res_dlt = { type = "float" },
    gint_campaign_exittomenu_status = { type = "int" },
    gint_campaign_selectedcampaign = { type = "int" },
    gint_campaign_selectedmission = { type = "int" },
    gint_count_pause = { type = "int" },
    gint_dbg_logrequestsoundcount = { type = "int" },
    gint_dbg_logsoundcount = { type = "int" },
    gint_editor_selectedcountryid = { type = "int" },
    gint_editor_selectedunitid = { type = "int" },
    gint_gui_achwinlose = { type = "int" },
    gint_gui_adviserwidth = { type = "int" },
    gint_gui_alarmevent = { type = "int" },
    gint_gui_alliancebtnclicked = { type = "int" },
    gint_gui_alliancevisible = { type = "int" },
    gint_gui_announcementstate = { type = "int" },
    gint_gui_changeresolutionmode = { type = "int" },
    gint_gui_changeresolutionstage = { type = "int" },
    gint_gui_chatind = { type = "int" },
    gint_gui_chatmessagemode = { type = "int" },
    gint_gui_connectserverstate = { type = "int" },
    gint_gui_editormode = { type = "int" },
    gint_gui_encyclopedia_cid = { type = "int" },
    gint_gui_encyclopediapage = { type = "int" },
    gint_gui_hotkeytoedit = { type = "int" },
    gint_gui_lanrequestjoinsessionid = { type = "int" },
    gint_gui_lansendreadytries = { type = "int" },
    gint_gui_lansendstarttries = { type = "int" },
    gint_gui_lastprogressach = { type = "int" },
    gint_gui_market_buyrestype = { type = "int" },
    gint_gui_market_resamount = { type = "int" },
    gint_gui_market_sellrestype = { type = "int" },
    gint_gui_newsinternetconnection = { type = "int" },
    gint_gui_newsnextpage = { type = "int" },
    gint_gui_newsshowvisible = { type = "int" },
    gint_gui_newsunique = { type = "int" },
    gint_gui_officer_formationsizedecrease = { type = "int" },
    gint_gui_officer_formationsizedecreasemax = { type = "int" },
    gint_gui_officer_selectedformation = { type = "int" },
    gint_gui_pickedbldcid = { type = "int" },
    gint_gui_pickedbldhnd = { type = "int" },
    gint_gui_prevelementpressed = { type = "int" },
    gint_gui_prevelementundermouse = { type = "int" },
    gint_gui_prevshowunitcontrolunituid = { type = "int" },
    gint_gui_prevundercursoruid = { type = "int" },
    gint_gui_progressbar_picnum = { type = "int" },
    gint_gui_progresstick = { type = "int" },
    gint_gui_progresstickeditor = { type = "int" },
    gint_gui_reloadflag = { type = "int" },
    gint_gui_revertresolutiontimer = { type = "float" },
    gint_gui_saveload_enum = { type = "int" },
    gint_gui_saveload_ind = { type = "int" },
    gint_gui_saveload_mode = { type = "int" },
    gint_gui_selectedplayertrade = { type = "int" },
    gint_gui_sliderdragx = { type = "int" },
    gint_gui_sliderdragy = { type = "int" },
    gint_gui_sliderhnd = { type = "int" },
    gint_gui_soundtag = { type = "int" },
    gint_gui_tournamentwinvisible = { type = "int" },
    gint_gui_unitcontrolsquadind = { type = "int" },
    gint_gui_unitcontroluid = { type = "int" },
    gint_gui_update_highlights_progresstick = { type = "int" },
    gint_gui_update_unitcontrol_progresstick = { type = "int" },
    gint_gui_updateclientlist = { type = "int" },
    gint_gui_updatesessionlist = { type = "int" },
    gint_gui_videoscreenshotphase = { type = "int" },
    gint_internetshell_msgplid = { type = "int" },
    gint_internetshell_prevplholder = { type = "int" },
    gint_internetshell_toppanelvisible = { type = "int" },
    gint_internetshell_tournamentsorstreams = { type = "int" },
    gint_maxcountrycountplayable = { type = "int" },
    gint_maxcountrycountvisible = { type = "int" },
    gint_net_myindex = { type = "int" },
    gint_news_gowithouttimer = { type = "int" },
    gint_news_limiter = { type = "int" },
    gint_news_manual = { type = "int" },
    gint_news_onceloadbarstep = { type = "int" },
    gint_news_reverse = { type = "int" },
    gint_perf_progressind = { type = "int" },
    gint_quickplay_countofplayers = { type = "int" },
    gint_searchenemy_count = { type = "int" },
    gint_searchenemy_progress = { type = "int" },
    gint_searchenemy_skiptickcount = { type = "int" },
    gint_settings_hotkeyspage = { type = "int" },
    gint_soundsteptick = { type = "int" },
    gint_unit_parentcid = { type = "int" },
    gint_unit_tagstate = { type = "int" },
    gint_versionid = { type = "int" },
    gpointer_register0 = { type = "int" },
    gstring_campaign_exittomenu_campname = { type = "string" },
    gstring_campaign_exittomenu_missname = { type = "string" },
    gstring_campaign_lastmissionname = { type = "string" },
    gstring_campaign_selcampaignname = { type = "string" },
    gstring_campaign_selmissionname = { type = "string" },
    gstring_checksum = { type = "string" },
    gstring_checksumlong = { type = "string" },
    gstring_editor_lastgenbitmapname = { type = "string" },
    gstring_editor_lastgenmapname = { type = "string" },
    gstring_editor_selectedcountrysid = { type = "string" },
    gstring_editor_selectedunitsid = { type = "string" },
    gstring_gui_connectserver = { type = "string" },
    gstring_gui_eventpressstate = { type = "string" },
    gstring_gui_lastguisoundname = { type = "string" },
    gstring_gui_saveload_name = { type = "string" },
    gstring_gui_saving = { type = "string" },
    gstring_internetshell_msgplnick = { type = "string" },
    gstring_news_version = { type = "string" },
    gstring_roomchecksum = { type = "string" },
    gstring_validpagestoshow = { type = "string" },
  },
}
